/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Schedule
         * @description Generate optimized schedule for matches.
         *
         *     This is a stateless endpoint - all data is provided in the request,
         *     and the schedule is returned without persistence.
         *
         *     Args:
         *         request: Contains tournament config, players, and matches
         *
         *     Returns:
         *         Optimized schedule with match assignments
         */
        post: operations["generate_schedule_schedule_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Schedule Stream
         * @description Generate schedule with real-time progress updates via Server-Sent Events.
         *
         *     Event types streamed (JSON after ``data:`` prefix):
         *
         *     - ``{type: 'model_built', numMatches, numIntervals, numNoOverlap, numVariables, ...}``
         *       emitted once, after ``scheduler.build()`` completes.
         *     - ``{type: 'phase', phase: 'presolve' | 'search' | 'proving'}``
         *       emitted on phase transitions (see below).
         *     - ``{type: 'progress', ...}`` — each intermediate solution.
         *     - ``{type: 'complete', result: ScheduleDTO}`` — final result.
         *     - ``{type: 'error', message: str}`` — on solver exception.
         *     - ``{type: 'done'}`` — always the last event; stream terminator.
         *
         *     Phase state machine: presolve → search (on first solution) → proving
         *     (on optimal final status).
         */
        post: operations["generate_schedule_stream_schedule_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Schedule Move
         * @description Cheap (pure-Python) feasibility check for a drag-to-reschedule move.
         *
         *     No CP-SAT invocation. Used by the frontend during a drag to paint a red
         *     ring on the target cell when the proposed (slot, court) would violate a
         *     hard constraint. Target latency: <50 ms.
         */
        post: operations["validate_schedule_move_schedule_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule/repair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Repair Schedule
         * @description Re-solve the affected slice; everything else stays put.
         */
        post: operations["repair_schedule_schedule_repair_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule/warm-restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Warm Restart Schedule
         * @description Re-solve the whole problem with a stay-close bias.
         */
        post: operations["warm_restart_schedule_schedule_warm_restart_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule/advisories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Schedule Advisories
         * @description Return current advisories computed from tournament + match state.
         *
         *     Reads both files via the existing helpers in tournament_state /
         *     match_state. Returns ``[]`` when nothing actionable is detected (or
         *     when the tournament hasn't been configured yet).
         *
         *     Also posts REPAIR triggers to the SuggestionsWorker for any advisory
         *     whose suggestedAction.kind is 'repair', and attaches a ``suggestionId``
         *     to advisories that already have a pre-baked suggestion stamped by the
         *     worker.
         */
        get: operations["get_schedule_advisories_schedule_advisories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule/proposals/warm-restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Warm Restart Proposal
         * @description Run a stay-close warm-restart and stash the result as a proposal.
         */
        post: operations["create_warm_restart_proposal_schedule_proposals_warm_restart_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule/proposals/repair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Repair Proposal
         * @description Run a slice-based repair and stash the result as a proposal.
         *
         *     For ``court_closed`` disruptions we also propose a config update
         *     that appends the closed court id to ``config.closedCourts`` —
         *     otherwise a subsequent re-solve would silently route matches back
         *     onto the closed court. Commit persists both schedule + config
         *     atomically.
         */
        post: operations["create_repair_proposal_schedule_proposals_repair_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule/proposals/manual-edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Manual Edit Proposal
         * @description Pin one match to a new slot/court via warm-restart, high stay-close.
         *
         *     The drag-and-drop UX feeds this endpoint. Other matches only move
         *     when the pinned target makes their existing positions infeasible.
         */
        post: operations["create_manual_edit_proposal_schedule_proposals_manual_edit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule/proposals/{proposal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Proposal
         * @description Re-fetch a proposal by id (e.g., after a page reload).
         */
        get: operations["get_proposal_schedule_proposals__proposal_id__get"];
        put?: never;
        post?: never;
        /**
         * Cancel Proposal
         * @description Discard a proposal without committing.
         */
        delete: operations["cancel_proposal_schedule_proposals__proposal_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule/proposals/{proposal_id}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Commit Proposal
         * @description Atomically apply a proposal to the persisted tournament state.
         *
         *     Optimistic-concurrency-checked: if the committed ``scheduleVersion``
         *     has advanced since the proposal was created, the commit is rejected
         *     with 409 and the operator must re-create the proposal.
         *
         *     The lock around the read-version-check / write / delete window
         *     prevents a second concurrent commit on the same proposal id from
         *     seeing it exist, advancing the version, and double-committing.
         */
        post: operations["commit_proposal_schedule_proposals__proposal_id__commit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule/director-action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Director Action
         * @description Create a proposal from a director time-axis action.
         *
         *     Routes through the same proposal pipeline as replan/repair so the
         *     operator reviews the full impact (which matches move, what the new
         *     finish time is, any infeasibility warnings) before committing.
         *
         *     The lock is held only across the proposal-store mutation; the
         *     solver call itself runs outside the lock so concurrent director
         *     actions can solve in parallel — they only serialize when storing
         *     the proposal.
         */
        post: operations["create_director_action_schedule_director_action_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Suggestions
         * @description Active suggestions, sorted by severity then creation time.
         *
         *     Drops expired entries before returning. The frontend polls this
         *     endpoint every ~8s and rebuilds the rail from the response.
         */
        get: operations["list_suggestions_schedule_suggestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule/suggestions/{suggestion_id}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply Suggestion
         * @description Commit the proposal underlying a suggestion.
         *
         *     Drops the suggestion before invoking commit so a 409 (stale
         *     version) doesn't leave a dead entry in the inbox — the
         *     frontend's next poll will reconcile.
         */
        post: operations["apply_suggestion_schedule_suggestions__suggestion_id__apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule/suggestions/{suggestion_id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dismiss Suggestion
         * @description Drop a suggestion and cancel its underlying proposal.
         */
        post: operations["dismiss_suggestion_schedule_suggestions__suggestion_id__dismiss_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/match-states": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Match States
         * @description Get all match states.
         */
        get: operations["get_all_match_states_match_states_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/match-states/{match_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Match State
         * @description Get a single match state, or a default `scheduled` if unseen.
         */
        get: operations["get_match_state_match_states__match_id__get"];
        /**
         * Update Match State
         * @description Update a match state.
         */
        put: operations["update_match_state_match_states__match_id__put"];
        post?: never;
        /**
         * Delete Match State
         * @description Remove a match state (reset to default).
         */
        delete: operations["delete_match_state_match_states__match_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/match-states/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset All Match States
         * @description Clear all match states (empty the file).
         */
        post: operations["reset_all_match_states_match_states_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/match-states/export/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Match States
         * @description Download the match_states.json file.
         */
        get: operations["export_match_states_match_states_export_download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/match-states/import/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Match States
         * @description Upload and import a match_states.json file.
         */
        post: operations["import_match_states_match_states_import_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/match-states/import-bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Match States Bulk
         * @description Merge a dict of match states into the existing file.
         */
        post: operations["import_match_states_bulk_match_states_import_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournament/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tournament State
         * @description Return the persisted tournament state.
         *
         *     204 No Content when no state has been saved yet. Payload gains a
         *     ``recoveredFromBackup`` field when a corrupt file was auto-repaired.
         */
        get: operations["get_tournament_state_tournament_state_get"];
        /**
         * Put Tournament State
         * @description Overwrite the tournament state atomically.
         *
         *     Backup of the previous live file is rotated before the new state is
         *     written. The server stamps ``updatedAt`` so two tabs can agree on
         *     ordering.
         */
        put: operations["put_tournament_state_tournament_state_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournament/state/backups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tournament Backups
         * @description Return the rolling-backup list, newest first.
         */
        get: operations["list_tournament_backups_tournament_state_backups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournament/state/backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Tournament Backup
         * @description Manually snapshot the current live file into the backup pool.
         */
        post: operations["create_tournament_backup_tournament_state_backup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournament/state/restore/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore Tournament Backup
         * @description Replace the live file with the chosen backup, atomically.
         */
        post: operations["restore_tournament_backup_tournament_state_restore__filename__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Shallow liveness probe — the container is up.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/deep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Deep
         * @description Deep readiness probe.
         *
         *     Verifies the data directory is writable and the CP-SAT solver module
         *     imports successfully. Used by the Docker HEALTHCHECK so orchestrators
         *     can catch "backend is up but can't persist" failure modes.
         */
        get: operations["health_deep_health_deep_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Advisory
         * @description A live-operations recommendation surfaced to the operator.
         *
         *     Produced by `GET /schedule/advisories` from the current match-state +
         *     tournament-state snapshot. Stable `id` lets clients dedupe across
         *     polling cycles even as `summary` drifts (e.g., overrun gets worse).
         */
        Advisory: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "overrun" | "no_show" | "running_behind" | "infeasibility_risk" | "start_delay_detected" | "approaching_blackout";
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warn" | "critical";
            /** Summary */
            summary: string;
            /** Detail */
            detail?: string | null;
            /** Matchid */
            matchId?: string | null;
            /** Courtid */
            courtId?: number | null;
            suggestedAction?: components["schemas"]["SuggestedAction"] | null;
            /** Suggestionid */
            suggestionId?: string | null;
            /** Detectedat */
            detectedAt: string;
        };
        /** AvailabilityWindow */
        AvailabilityWindow: {
            /** Start */
            start: string;
            /** End */
            end: string;
        };
        /** BackupCreatedDTO */
        BackupCreatedDTO: {
            /** Filename */
            filename?: string | null;
            /** Created */
            created: boolean;
        };
        /** BackupEntryDTO */
        BackupEntryDTO: {
            /** Filename */
            filename: string;
            /** Sizebytes */
            sizeBytes: number;
            /** Modifiedat */
            modifiedAt: string;
        };
        /** BackupListDTO */
        BackupListDTO: {
            /** Backups */
            backups: components["schemas"]["BackupEntryDTO"][];
        };
        /** Body_import_match_states_match_states_import_upload_post */
        Body_import_match_states_match_states_import_upload_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** BreakWindow */
        BreakWindow: {
            /** Start */
            start: string;
            /** End */
            end: string;
        };
        /**
         * CommitResponse
         * @description Response payload from a successful proposal commit.
         */
        CommitResponse: {
            state: components["schemas"]["TournamentStateDTO-Output"];
            historyEntry: components["schemas"]["ScheduleHistoryEntry-Output"];
        };
        /**
         * CourtClosure
         * @description A court closure window. ``fromTime`` / ``toTime`` are HH:mm
         *     wall-clock bounds inside the tournament day. Either may be omitted:
         *
         *     - both omitted → court is closed all day (indefinite)
         *     - only ``fromTime`` omitted → closed from start of day to ``toTime``
         *     - only ``toTime`` omitted → closed from ``fromTime`` to end of day
         *
         *     The solver translates the bounds to slot indices via the same
         *     rounding ``time_to_slot`` uses for breaks.
         */
        CourtClosure: {
            /** Courtid */
            courtId: number;
            /** Fromtime */
            fromTime?: string | null;
            /** Totime */
            toTime?: string | null;
            /** Reason */
            reason?: string | null;
        };
        /**
         * DirectorAction
         * @description A single director-tool invocation. Discriminated by ``kind``.
         *
         *     Only the fields relevant to the chosen kind need to be set; the
         *     others are ignored. (We avoid a discriminated-union here because
         *     the frontend already round-trips a flat dict per the existing
         *     Disruption shape.)
         */
        DirectorAction: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "delay_start" | "insert_blackout" | "remove_blackout" | "reopen_court";
            /** Minutes */
            minutes?: number | null;
            /** Fromtime */
            fromTime?: string | null;
            /** Totime */
            toTime?: string | null;
            /** Reason */
            reason?: string | null;
            /** Blackoutindex */
            blackoutIndex?: number | null;
            /** Courtid */
            courtId?: number | null;
        };
        /** DirectorActionRequest */
        DirectorActionRequest: {
            action: components["schemas"]["DirectorAction"];
            config: components["schemas"]["TournamentConfig"];
            /** Players */
            players: components["schemas"]["PlayerDTO"][];
            /** Matches */
            matches: components["schemas"]["MatchDTO"][];
            originalSchedule: components["schemas"]["ScheduleDTO-Input"];
            /**
             * Matchstates
             * @default {}
             */
            matchStates: {
                [key: string]: components["schemas"]["MatchStateDTO"];
            };
        };
        /**
         * Disruption
         * @description One disruption that triggers a repair.
         *
         *     Fields are optional individually but the *combination* is
         *     determined by ``type``:
         *       - ``withdrawal``  → ``playerId`` required
         *       - ``court_closed`` → ``courtId`` required; ``fromTime`` /
         *         ``toTime`` optional (omit both for an indefinite all-day
         *         closure, supply both for a temporary window)
         *       - ``overrun``     → ``matchId`` required, ``extraMinutes`` optional
         *       - ``cancellation`` → ``matchId`` required
         */
        Disruption: {
            /**
             * Type
             * @enum {string}
             */
            type: "withdrawal" | "court_closed" | "overrun" | "cancellation";
            /** Playerid */
            playerId?: string | null;
            /** Courtid */
            courtId?: number | null;
            /** Matchid */
            matchId?: string | null;
            /** Extraminutes */
            extraMinutes?: number | null;
            /** Fromtime */
            fromTime?: string | null;
            /** Totime */
            toTime?: string | null;
            /** Reason */
            reason?: string | null;
        };
        /**
         * GenerateScheduleRequest
         * @description Request to generate a schedule - includes all data needed.
         */
        GenerateScheduleRequest: {
            config: components["schemas"]["TournamentConfig"];
            /** Players */
            players: components["schemas"]["PlayerDTO"][];
            /** Matches */
            matches: components["schemas"]["MatchDTO"][];
            /** Previousassignments */
            previousAssignments?: components["schemas"]["PreviousAssignmentDTO"][] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Impact
         * @description Pre-commit diff produced by the proposal pipeline.
         *
         *     Computed once when a proposal is created and stashed alongside it,
         *     so reviewing the same proposal later doesn't re-run the diff.
         *
         *     ``clockShiftMinutesDelta`` is non-zero only for director ``delay_start``
         *     proposals — those don't move any matches in slot-space but do shift
         *     the displayed wall-clock for every unstarted match.
         */
        Impact: {
            /** Movedmatches */
            movedMatches?: components["schemas"]["MatchMove"][];
            /** Affectedplayers */
            affectedPlayers?: components["schemas"]["PlayerImpact"][];
            /** Affectedschools */
            affectedSchools?: components["schemas"]["SchoolImpact"][];
            metricDelta?: components["schemas"]["MetricDelta"];
            /** Infeasibilitywarnings */
            infeasibilityWarnings?: string[];
            /**
             * Clockshiftminutesdelta
             * @default 0
             */
            clockShiftMinutesDelta: number;
        };
        /**
         * ManualEditRequest
         * @description Drag-pin a single match to a new slot/court and warm-restart with a
         *     high stay-close weight so nothing else moves unless feasibility forces it.
         */
        ManualEditRequest: {
            originalSchedule: components["schemas"]["ScheduleDTO-Input"];
            config: components["schemas"]["TournamentConfig"];
            /** Players */
            players: components["schemas"]["PlayerDTO"][];
            /** Matches */
            matches: components["schemas"]["MatchDTO"][];
            /**
             * Groups
             * @default []
             */
            groups: components["schemas"]["RosterGroupDTO"][];
            /**
             * Matchstates
             * @default {}
             */
            matchStates: {
                [key: string]: components["schemas"]["MatchStateDTO"];
            };
            /** Matchid */
            matchId: string;
            /** Pinnedslotid */
            pinnedSlotId: number;
            /** Pinnedcourtid */
            pinnedCourtId: number;
        };
        /** MatchDTO */
        MatchDTO: {
            /** Id */
            id: string;
            /** Matchnumber */
            matchNumber?: number | null;
            /** Sidea */
            sideA?: string[];
            /** Sideb */
            sideB?: string[];
            /** Sidec */
            sideC?: string[] | null;
            /**
             * Matchtype
             * @default dual
             */
            matchType: string;
            /** Eventrank */
            eventRank?: string | null;
            /**
             * Durationslots
             * @default 1
             */
            durationSlots: number;
            /** Preferredcourt */
            preferredCourt?: number | null;
            /** Tags */
            tags?: string[] | null;
        };
        /**
         * MatchMove
         * @description One match's slot/court change between committed and proposed schedules.
         */
        MatchMove: {
            /** Matchid */
            matchId: string;
            /** Fromslotid */
            fromSlotId?: number | null;
            /** Toslotid */
            toSlotId?: number | null;
            /** Fromcourtid */
            fromCourtId?: number | null;
            /** Tocourtid */
            toCourtId?: number | null;
            /** Matchnumber */
            matchNumber?: number | null;
            /** Eventrank */
            eventRank?: string | null;
        };
        /** MatchScore */
        MatchScore: {
            /** Sidea */
            sideA: number;
            /** Sideb */
            sideB: number;
        };
        /** MatchStateDTO */
        MatchStateDTO: {
            /** Matchid */
            matchId: string;
            /**
             * Status
             * @default scheduled
             * @enum {string}
             */
            status: "scheduled" | "called" | "started" | "finished";
            /** Calledat */
            calledAt?: string | null;
            /** Actualstarttime */
            actualStartTime?: string | null;
            /** Actualendtime */
            actualEndTime?: string | null;
            score?: components["schemas"]["MatchScore"] | null;
            /** Notes */
            notes?: string | null;
            /** Updatedat */
            updatedAt?: string | null;
            /** Originalslotid */
            originalSlotId?: number | null;
            /** Originalcourtid */
            originalCourtId?: number | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * MetricDelta
         * @description Signed differences between proposed and committed schedules.
         *
         *     Positive = proposed is *worse* on that axis (more violations / higher
         *     penalty). UI surfaces these with conventional improvement-is-good
         *     coloring: `restViolationsDelta < 0` is green, `> 0` is red.
         */
        MetricDelta: {
            /** Objectivedelta */
            objectiveDelta?: number | null;
            /**
             * Softviolationcountdelta
             * @default 0
             */
            softViolationCountDelta: number;
            /**
             * Restviolationsdelta
             * @default 0
             */
            restViolationsDelta: number;
            /**
             * Proximityviolationsdelta
             * @default 0
             */
            proximityViolationsDelta: number;
            /**
             * Totalpenaltydelta
             * @default 0
             */
            totalPenaltyDelta: number;
            /**
             * Unscheduledmatchesdelta
             * @default 0
             */
            unscheduledMatchesDelta: number;
        };
        /** PlayerDTO */
        PlayerDTO: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Groupid */
            groupId: string;
            /** Ranks */
            ranks?: string[];
            /** Availability */
            availability?: components["schemas"]["AvailabilityWindow"][];
            /** Minrestminutes */
            minRestMinutes?: number | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * PlayerImpact
         * @description Aggregate of how a single player's day changes.
         */
        PlayerImpact: {
            /** Playerid */
            playerId: string;
            /** Playername */
            playerName?: string | null;
            /** Matchcount */
            matchCount: number;
            /** Earliestslotdelta */
            earliestSlotDelta: number;
        };
        /**
         * PreviousAssignmentDTO
         * @description Typed previous assignment used by /schedule re-solve and drag pin-and-resolve.
         */
        PreviousAssignmentDTO: {
            /** Matchid */
            matchId: string;
            /** Slotid */
            slotId: number;
            /** Courtid */
            courtId: number;
            /**
             * Locked
             * @default false
             */
            locked: boolean;
            /** Pinnedslotid */
            pinnedSlotId?: number | null;
            /** Pinnedcourtid */
            pinnedCourtId?: number | null;
        };
        /**
         * Proposal
         * @description A pending schedule change awaiting operator confirmation.
         *
         *     Created by `POST /schedule/proposals/...`, kept in memory with a TTL,
         *     and applied to the persisted tournament state via the commit endpoint.
         *     The `fromScheduleVersion` snapshot is what the optimistic-concurrency
         *     check at commit time compares against — if the committed schedule
         *     has advanced since proposal creation, the commit is rejected with 409.
         *
         *     ``proposedConfig`` is non-None only for director-action proposals —
         *     those mutate ``TournamentConfig`` (clockShiftMinutes, breaks, ...)
         *     in addition to the schedule. Commit applies both atomically.
         */
        Proposal: {
            /** Id */
            id: string;
            kind: components["schemas"]["ProposalKind"];
            proposedSchedule: components["schemas"]["ScheduleDTO-Output"];
            proposedConfig?: components["schemas"]["TournamentConfig"] | null;
            impact: components["schemas"]["Impact"];
            /** Summary */
            summary?: string | null;
            /** Fromscheduleversion */
            fromScheduleVersion: number;
            /** Createdat */
            createdAt: string;
            /** Expiresat */
            expiresAt: string;
        };
        /**
         * ProposalKind
         * @enum {string}
         */
        ProposalKind: "warm_restart" | "repair" | "manual_edit" | "director_action";
        /**
         * ProposedMoveDTO
         * @description A single drag target evaluated by /schedule/validate.
         */
        ProposedMoveDTO: {
            /** Matchid */
            matchId: string;
            /** Slotid */
            slotId: number;
            /** Courtid */
            courtId: number;
        };
        /** RepairRequest */
        RepairRequest: {
            originalSchedule: components["schemas"]["ScheduleDTO-Input"];
            config: components["schemas"]["TournamentConfig"];
            /** Players */
            players: components["schemas"]["PlayerDTO"][];
            /** Matches */
            matches: components["schemas"]["MatchDTO"][];
            /**
             * Matchstates
             * @default {}
             */
            matchStates: {
                [key: string]: components["schemas"]["MatchStateDTO"];
            };
            disruption: components["schemas"]["Disruption"];
            /** Nowiso */
            nowIso?: string | null;
            /** Timebudgetsec */
            timeBudgetSec?: number | null;
        };
        /** RepairResponse */
        RepairResponse: {
            schedule: components["schemas"]["ScheduleDTO-Output"];
            /** Repairedmatchids */
            repairedMatchIds: string[];
        };
        /** RosterGroupDTO */
        RosterGroupDTO: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /** ScheduleAssignment */
        ScheduleAssignment: {
            /** Matchid */
            matchId: string;
            /** Slotid */
            slotId: number;
            /** Courtid */
            courtId: number;
            /** Durationslots */
            durationSlots: number;
        };
        /**
         * ScheduleCandidate
         * @description One alternative schedule the solver found while improving.
         *
         *     The pool is captured during the initial solve; operator can swap
         *     the active candidate without a re-solve. ``solutionId`` is a stable
         *     id for React keys; ``objectiveScore`` lets the UI show how each
         *     candidate ranks; ``foundAtSeconds`` is wall-clock seconds since
         *     solve start (lower = solver's earlier guess, often more disrupted).
         */
        ScheduleCandidate: {
            /** Solutionid */
            solutionId: string;
            /** Assignments */
            assignments?: components["schemas"]["ScheduleAssignment"][];
            /**
             * Objectivescore
             * @default 0
             */
            objectiveScore: number;
            /**
             * Foundatseconds
             * @default 0
             */
            foundAtSeconds: number;
        };
        /** ScheduleDTO */
        "ScheduleDTO-Input": {
            /** Assignments */
            assignments?: components["schemas"]["ScheduleAssignment"][];
            /** Unscheduledmatches */
            unscheduledMatches?: string[];
            /** Softviolations */
            softViolations?: components["schemas"]["SoftViolation"][];
            /** Objectivescore */
            objectiveScore?: number | null;
            /** Infeasiblereasons */
            infeasibleReasons?: string[];
            status: components["schemas"]["SolverStatus"];
            /** Solverseed */
            solverSeed?: number | null;
            /** Candidates */
            candidates?: components["schemas"]["ScheduleCandidate"][];
            /** Activecandidateindex */
            activeCandidateIndex?: number | null;
        };
        /** ScheduleDTO */
        "ScheduleDTO-Output": {
            /** Assignments */
            assignments?: components["schemas"]["ScheduleAssignment"][];
            /** Unscheduledmatches */
            unscheduledMatches?: string[];
            /** Softviolations */
            softViolations?: components["schemas"]["SoftViolation"][];
            /** Objectivescore */
            objectiveScore?: number | null;
            /** Infeasiblereasons */
            infeasibleReasons?: string[];
            status: components["schemas"]["SolverStatus"];
            /** Solverseed */
            solverSeed?: number | null;
            /** Candidates */
            candidates?: components["schemas"]["ScheduleCandidate"][];
            /** Activecandidateindex */
            activeCandidateIndex?: number | null;
        };
        /**
         * ScheduleHistoryEntry
         * @description Snapshot of a prior committed schedule, kept for revert + audit.
         *
         *     Appended whenever a proposal is committed; the entry captures the
         *     schedule that was *replaced*, not the new one. Capped at 5 entries
         *     server-side (oldest dropped first) so the persisted state file stays
         *     bounded.
         */
        "ScheduleHistoryEntry-Input": {
            /** Version */
            version: number;
            /** Committedat */
            committedAt: string;
            /** Trigger */
            trigger?: string | null;
            /** Summary */
            summary?: string | null;
            schedule?: components["schemas"]["ScheduleDTO-Input"] | null;
        };
        /**
         * ScheduleHistoryEntry
         * @description Snapshot of a prior committed schedule, kept for revert + audit.
         *
         *     Appended whenever a proposal is committed; the entry captures the
         *     schedule that was *replaced*, not the new one. Capped at 5 entries
         *     server-side (oldest dropped first) so the persisted state file stays
         *     bounded.
         */
        "ScheduleHistoryEntry-Output": {
            /** Version */
            version: number;
            /** Committedat */
            committedAt: string;
            /** Trigger */
            trigger?: string | null;
            /** Summary */
            summary?: string | null;
            schedule?: components["schemas"]["ScheduleDTO-Output"] | null;
        };
        /**
         * SchoolImpact
         * @description Aggregate of how a single roster group's day changes.
         */
        SchoolImpact: {
            /** Groupid */
            groupId: string;
            /** Groupname */
            groupName?: string | null;
            /** Matchcount */
            matchCount: number;
        };
        /** SoftViolation */
        SoftViolation: {
            /** Type */
            type: string;
            /** Matchid */
            matchId?: string | null;
            /** Playerid */
            playerId?: string | null;
            /** Description */
            description: string;
            /** Penaltyincurred */
            penaltyIncurred: number;
        };
        /**
         * SolverStatus
         * @enum {string}
         */
        SolverStatus: "optimal" | "feasible" | "infeasible" | "unknown";
        /**
         * SuggestedAction
         * @description A pre-filled action the UI can offer as a one-click resolve.
         */
        SuggestedAction: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "warm_restart" | "repair" | "delay_start" | "insert_blackout" | "compress_remaining" | "remove_blackout";
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
        };
        /**
         * Suggestion
         * @description A pre-computed re-optimization proposal surfaced in the inbox.
         *
         *     Wraps a (still-live) ``Proposal`` with display copy and a dedup
         *     fingerprint. The frontend reads these from
         *     ``GET /schedule/suggestions``; ``apply`` commits the underlying
         *     proposal; ``dismiss`` cancels it.
         *
         *     ``fingerprint`` is the worker's idempotency key — re-running the
         *     same trigger against the same state yields the same fingerprint,
         *     so the worker can skip stamping a duplicate suggestion.
         */
        Suggestion: {
            /** Id */
            id?: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "repair" | "optimize" | "director" | "candidate";
            /** Title */
            title: string;
            /** Metric */
            metric: string;
            /** Proposalid */
            proposalId: string;
            /** Fingerprint */
            fingerprint: string;
            /** Fromscheduleversion */
            fromScheduleVersion: number;
            /** Createdat */
            createdAt?: string;
            /** Expiresat */
            expiresAt: string;
        };
        /** TournamentConfig */
        TournamentConfig: {
            /** Tournamentname */
            tournamentName?: string | null;
            /** Meetmode */
            meetMode?: ("dual" | "tri") | null;
            /** Intervalminutes */
            intervalMinutes: number;
            /** Daystart */
            dayStart: string;
            /** Dayend */
            dayEnd: string;
            /** Tournamentdate */
            tournamentDate?: string | null;
            /** Breaks */
            breaks?: components["schemas"]["BreakWindow"][];
            /** Courtcount */
            courtCount: number;
            /** Defaultrestminutes */
            defaultRestMinutes: number;
            /** Freezehorizonslots */
            freezeHorizonSlots: number;
            /** Rankcounts */
            rankCounts?: {
                [key: string]: number;
            };
            /**
             * Enablecourtutilization
             * @default true
             */
            enableCourtUtilization: boolean | null;
            /**
             * Courtutilizationpenalty
             * @default 50
             */
            courtUtilizationPenalty: number | null;
            /**
             * Enablegameproximity
             * @default false
             */
            enableGameProximity: boolean | null;
            /** Mingamespacingslots */
            minGameSpacingSlots?: number | null;
            /** Maxgamespacingslots */
            maxGameSpacingSlots?: number | null;
            /**
             * Gameproximitypenalty
             * @default 5
             */
            gameProximityPenalty: number | null;
            /**
             * Enablecompactschedule
             * @default false
             */
            enableCompactSchedule: boolean | null;
            /**
             * Compactschedulemode
             * @default minimize_makespan
             */
            compactScheduleMode: ("minimize_makespan" | "no_gaps" | "finish_by_time") | null;
            /**
             * Compactschedulepenalty
             * @default 100
             */
            compactSchedulePenalty: number | null;
            /** Targetfinishslot */
            targetFinishSlot?: number | null;
            /**
             * Allowplayeroverlap
             * @default false
             */
            allowPlayerOverlap: boolean | null;
            /**
             * Playeroverlappenalty
             * @default 50
             */
            playerOverlapPenalty: number | null;
            /** Scoringformat */
            scoringFormat?: ("simple" | "badminton") | null;
            /** Setstowin */
            setsToWin?: number | null;
            /** Pointsperset */
            pointsPerSet?: number | null;
            /** Deuceenabled */
            deuceEnabled?: boolean | null;
            /** Tvdisplaymode */
            tvDisplayMode?: ("strip" | "grid" | "list") | null;
            /** Tvaccent */
            tvAccent?: string | null;
            /** Tvpreset */
            tvPreset?: ("court" | "pitch" | "midnight" | "ash" | "paper" | "chalk" | "daylight" | "sand") | null;
            /** Tvgridcolumns */
            tvGridColumns?: number | null;
            /** Tvcardsize */
            tvCardSize?: ("auto" | "compact" | "comfortable" | "large") | null;
            /** Tvshowscores */
            tvShowScores?: boolean | null;
            /** Eventorder */
            eventOrder?: string[] | null;
            /** Eventvisible */
            eventVisible?: {
                [key: string]: boolean;
            } | null;
            /** Deterministic */
            deterministic?: boolean | null;
            /** Randomseed */
            randomSeed?: number | null;
            /** Solvertimelimitseconds */
            solverTimeLimitSeconds?: number | null;
            /** Candidatepoolsize */
            candidatePoolSize?: number | null;
            /** Closedcourts */
            closedCourts?: number[];
            /** Courtclosures */
            courtClosures?: components["schemas"]["CourtClosure"][];
            /**
             * Clockshiftminutes
             * @default 0
             */
            clockShiftMinutes: number | null;
        };
        /**
         * TournamentStateDTO
         * @description Authoritative persisted state for one tournament.
         *
         *     Writes come as a single blob: frontend Zustand state snapshotted and
         *     PUT to /tournament/state. Server stamps `updatedAt` on write; the
         *     client's value is ignored.
         */
        "TournamentStateDTO-Input": {
            /**
             * Version
             * @default 1
             */
            version: number;
            /** Updatedat */
            updatedAt?: string | null;
            config?: components["schemas"]["TournamentConfig"] | null;
            /** Groups */
            groups?: components["schemas"]["RosterGroupDTO"][];
            /** Players */
            players?: components["schemas"]["PlayerDTO"][];
            /** Matches */
            matches?: components["schemas"]["MatchDTO"][];
            schedule?: components["schemas"]["ScheduleDTO-Input"] | null;
            /** Schedulestats */
            scheduleStats?: {
                [key: string]: unknown;
            } | null;
            /**
             * Scheduleisstale
             * @default false
             */
            scheduleIsStale: boolean;
            /**
             * Scheduleversion
             * @default 0
             */
            scheduleVersion: number;
            /** Schedulehistory */
            scheduleHistory?: components["schemas"]["ScheduleHistoryEntry-Input"][];
        };
        /**
         * TournamentStateDTO
         * @description Authoritative persisted state for one tournament.
         *
         *     Writes come as a single blob: frontend Zustand state snapshotted and
         *     PUT to /tournament/state. Server stamps `updatedAt` on write; the
         *     client's value is ignored.
         */
        "TournamentStateDTO-Output": {
            /**
             * Version
             * @default 1
             */
            version: number;
            /** Updatedat */
            updatedAt?: string | null;
            config?: components["schemas"]["TournamentConfig"] | null;
            /** Groups */
            groups?: components["schemas"]["RosterGroupDTO"][];
            /** Players */
            players?: components["schemas"]["PlayerDTO"][];
            /** Matches */
            matches?: components["schemas"]["MatchDTO"][];
            schedule?: components["schemas"]["ScheduleDTO-Output"] | null;
            /** Schedulestats */
            scheduleStats?: {
                [key: string]: unknown;
            } | null;
            /**
             * Scheduleisstale
             * @default false
             */
            scheduleIsStale: boolean;
            /**
             * Scheduleversion
             * @default 0
             */
            scheduleVersion: number;
            /** Schedulehistory */
            scheduleHistory?: components["schemas"]["ScheduleHistoryEntry-Output"][];
        };
        /**
         * ValidateMoveRequest
         * @description Request to validate a single drag target without invoking CP-SAT.
         */
        ValidateMoveRequest: {
            config: components["schemas"]["TournamentConfig"];
            /** Players */
            players: components["schemas"]["PlayerDTO"][];
            /** Matches */
            matches: components["schemas"]["MatchDTO"][];
            /** Assignments */
            assignments: components["schemas"]["ScheduleAssignment"][];
            proposedMove: components["schemas"]["ProposedMoveDTO"];
            /** Previousassignments */
            previousAssignments?: components["schemas"]["PreviousAssignmentDTO"][] | null;
        };
        /**
         * ValidationConflict
         * @description One reason a proposed move or a full schedule is infeasible.
         */
        ValidationConflict: {
            /** Type */
            type: string;
            /** Description */
            description: string;
            /** Matchid */
            matchId?: string | null;
            /** Othermatchid */
            otherMatchId?: string | null;
            /** Playerid */
            playerId?: string | null;
            /** Courtid */
            courtId?: number | null;
            /** Slotid */
            slotId?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationResponseDTO */
        ValidationResponseDTO: {
            /** Feasible */
            feasible: boolean;
            /** Conflicts */
            conflicts?: components["schemas"]["ValidationConflict"][];
        };
        /** WarmRestartRequest */
        WarmRestartRequest: {
            originalSchedule: components["schemas"]["ScheduleDTO-Input"];
            config: components["schemas"]["TournamentConfig"];
            /** Players */
            players: components["schemas"]["PlayerDTO"][];
            /** Matches */
            matches: components["schemas"]["MatchDTO"][];
            /**
             * Matchstates
             * @default {}
             */
            matchStates: {
                [key: string]: components["schemas"]["MatchStateDTO"];
            };
            /**
             * Staycloseweight
             * @default 10
             */
            stayCloseWeight: number;
            /** Nowiso */
            nowIso?: string | null;
            /** Timebudgetsec */
            timeBudgetSec?: number | null;
        };
        /** WarmRestartResponse */
        WarmRestartResponse: {
            schedule: components["schemas"]["ScheduleDTO-Output"];
            /** Movedmatchids */
            movedMatchIds: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    generate_schedule_schedule_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateScheduleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleDTO-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_schedule_stream_schedule_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateScheduleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_schedule_move_schedule_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateMoveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    repair_schedule_schedule_repair_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepairRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepairResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    warm_restart_schedule_schedule_warm_restart_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WarmRestartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WarmRestartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_schedule_advisories_schedule_advisories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Advisory"][];
                };
            };
        };
    };
    create_warm_restart_proposal_schedule_proposals_warm_restart_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WarmRestartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_repair_proposal_schedule_proposals_repair_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepairRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_manual_edit_proposal_schedule_proposals_manual_edit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualEditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_proposal_schedule_proposals__proposal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_proposal_schedule_proposals__proposal_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    commit_proposal_schedule_proposals__proposal_id__commit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_director_action_schedule_director_action_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DirectorActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_suggestions_schedule_suggestions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Suggestion"][];
                };
            };
        };
    };
    apply_suggestion_schedule_suggestions__suggestion_id__apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                suggestion_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dismiss_suggestion_schedule_suggestions__suggestion_id__dismiss_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                suggestion_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_match_states_match_states_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["MatchStateDTO"];
                    };
                };
            };
        };
    };
    get_match_state_match_states__match_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchStateDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_match_state_match_states__match_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchStateDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchStateDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_match_state_match_states__match_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_all_match_states_match_states_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    export_match_states_match_states_export_download_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    import_match_states_match_states_import_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_match_states_match_states_import_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_match_states_bulk_match_states_import_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: components["schemas"]["MatchStateDTO"];
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tournament_state_tournament_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    put_tournament_state_tournament_state_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TournamentStateDTO-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TournamentStateDTO-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tournament_backups_tournament_state_backups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupListDTO"];
                };
            };
        };
    };
    create_tournament_backup_tournament_state_backup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupCreatedDTO"];
                };
            };
        };
    };
    restore_tournament_backup_tournament_state_restore__filename__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_deep_health_deep_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
