/**
 * Data Transfer Objects (DTOs).
 *
 * Contract types here mirror Pydantic models in
 * ``backend/app/schemas.py``. The auto-generated ``dto.generated.ts``
 * (produced by ``make generate-api`` from FastAPI's OpenAPI schema) is
 * the authoritative reference — when schemas.py changes, regenerate
 * dto.generated.ts and reconcile every drift in this file by hand.
 *
 * Frontend-private types (SSE event shapes, internal enums, importer
 * payloads, view discriminators) intentionally do NOT live in the
 * OpenAPI schema and are hand-written here.
 *
 * DO NOT EDIT THIS FILE WITHOUT VERIFYING IT MATCHES dto.generated.ts.
 */

// Tournament Configuration
export interface TournamentConfig {
  // Human-readable name. Used as a slug in backup filenames and as
  // the headline on the public TV display. Optional — when unset,
  // chrome falls back to "Tournament" / "tournament-<timestamp>".
  tournamentName?: string;
  // Per-tournament meet mode.
  //
  //   ``dual`` — exactly two schools play each other. The default.
  //   ``tri``  — three schools, full round-robin: every pair (A-B,
  //              A-C, B-C) plays each event TWICE so combined results
  //              decide the meet. Every individual match is still A
  //              vs B (one side per side, like dual) — there is no
  //              such thing as a "1v1v1" match in badminton.
  //
  // The auto-match generator branches on this; rendering surfaces
  // do not (matches always render as A vs B regardless of mode).
  meetMode?: 'dual' | 'tri';
  intervalMinutes: number;
  dayStart: string; // HH:mm format
  dayEnd: string; // HH:mm format
  tournamentDate?: string; // ISO date string: "2026-02-15"
  breaks: BreakWindow[];
  courtCount: number;
  defaultRestMinutes: number;
  freezeHorizonSlots: number;
  rankCounts?: Record<string, number>; // {"MS": 3, "WS": 3, "MD": 2, "WD": 4, "XD": 2}
  enableCourtUtilization?: boolean;
  courtUtilizationPenalty?: number;
  // Game proximity constraint
  enableGameProximity?: boolean;
  minGameSpacingSlots?: number | null;
  maxGameSpacingSlots?: number | null;
  gameProximityPenalty?: number;
  // Compact schedule - minimize makespan or eliminate gaps
  enableCompactSchedule?: boolean;
  compactScheduleMode?: 'minimize_makespan' | 'no_gaps' | 'finish_by_time';
  compactSchedulePenalty?: number;
  targetFinishSlot?: number | null;
  // Allow player overlap
  allowPlayerOverlap?: boolean;
  playerOverlapPenalty?: number;
  // Scoring format for badminton
  scoringFormat?: 'simple' | 'badminton';
  setsToWin?: number; // 1 (best of 1), 2 (best of 3), or 3 (best of 5)
  pointsPerSet?: number; // 11, 15, or 21
  deuceEnabled?: boolean; // Win by 2 in deuce (up to 30 for 21-point sets)
  // ---- Public TV display ------------------------------------------
  // How the public ``/display`` page renders the courts view.
  //
  //   strip — one tall row per court (default; best 3-6 courts, 1080p).
  //   grid  — 2-column responsive grid (best 8-16 courts).
  //   list  — dense one-line rows (best 16+ courts, side display).
  tvDisplayMode?: 'strip' | 'grid' | 'list';
  // Brand accent for the public display — hex (``#RRGGBB``). Drives
  // the LIVE border, the LIVE pill, and the progress bar. Defaults to
  // emerald (``#10b981``) when unset.
  tvAccent?: string;
  // Display preset id — selects the substrate palette (bg/text/border)
  // for the public ``/display`` page. See displayPresets.ts for the
  // full list (court, pitch, midnight, ash, paper, chalk, daylight,
  // sand). Defaults to ``court`` when unset.
  tvPreset?: string;
  // Force a specific column count for grid mode. ``null`` / unset =
  // auto (1-2 columns based on viewport).
  tvGridColumns?: 1 | 2 | 3 | 4 | null;
  // Card size — overrides the auto-sizing strip/grid layouts.
  // ``auto`` keeps the current behaviour; ``compact`` shrinks padding;
  // ``comfortable`` is the default tall card; ``large`` expands for
  // big-room viewing.
  tvCardSize?: 'auto' | 'compact' | 'comfortable' | 'large';
  // Whether to show the live score on the public display. Off when
  // the venue prefers to keep scores private until the match ends.
  tvShowScores?: boolean;
  // Optional event-column ordering and visibility for the Roster
  // position grid. Defaults to the canonical MD / WD / XD / WS / MS
  // sequence. Hidden columns are stored as ``false`` per rank.
  eventOrder?: string[];
  eventVisible?: Record<string, boolean>;
  // ---- Engine settings -------------------------------------------
  // Reproducible-run mode: solver runs single-threaded with a fixed
  // seed so the same input produces a byte-identical schedule across
  // runs. ~3× slower than parallel mode; default off.
  deterministic?: boolean;
  // Seed used in deterministic mode. Default 42 when unset.
  randomSeed?: number;
  // Solver wall-clock cap. The CP-SAT solver returns the best
  // feasible schedule found within this window. Higher = closer to
  // optimal at the cost of operator wait time. Default 30 s.
  solverTimeLimitSeconds?: number;
  // Director time-axis: minutes added to every unstarted match's
  // displayed wall-clock by `delay_start` actions. Solver still plans
  // on the abstract slot grid; this is purely a display offset.
  clockShiftMinutes?: number;
  // Court IDs (1-indexed) closed *all day* — the legacy shape kept
  // for backward compat with persisted state. New time-bounded
  // closures go into ``courtClosures`` below.
  closedCourts?: number[];
  // Time-bounded court closures. Each entry forbids the named
  // court inside its half-open ``[fromTime, toTime)`` window. Either
  // bound omitted means open-ended on that side; both omitted is
  // equivalent to a legacy ``closedCourts`` entry (full-day).
  courtClosures?: CourtClosure[];
  // How many near-optimal alternative schedules the solver keeps
  // alongside the chosen one. Operator can swap to a candidate in a
  // click when reality (overrun, withdrawal, court closure) makes
  // the chosen plan no longer fit — no re-solve needed. Default 5.
  candidatePoolSize?: number;
}

export interface CourtClosure {
  courtId: number;
  /** HH:mm; omit for "from start of day". */
  fromTime?: string;
  /** HH:mm; omit for "until end of day". */
  toTime?: string;
  reason?: string;
}

export interface BreakWindow {
  start: string; // HH:mm format
  end: string; // HH:mm format
}

export interface TournamentConfigDTO {
  intervalMinutes: number;
  dayStart: string;
  dayEnd: string;
  tournamentDate?: string; // ISO date string: "2026-02-15"
  breaks: BreakWindow[];
  courtCount: number;
  defaultRestMinutes: number;
  freezeHorizonSlots: number;
  rankCounts?: Record<string, number>;
  enableCourtUtilization?: boolean;
  courtUtilizationPenalty?: number;
  // Game proximity constraint
  enableGameProximity?: boolean;
  minGameSpacingSlots?: number | null;
  maxGameSpacingSlots?: number | null;
  gameProximityPenalty?: number;
  // Compact schedule - minimize makespan or eliminate gaps
  enableCompactSchedule?: boolean;
  compactScheduleMode?: 'minimize_makespan' | 'no_gaps' | 'finish_by_time';
  compactSchedulePenalty?: number;
  targetFinishSlot?: number | null;
  // Allow player overlap
  allowPlayerOverlap?: boolean;
  playerOverlapPenalty?: number;
  // Scoring format for badminton
  scoringFormat?: 'simple' | 'badminton';
  setsToWin?: number;
  pointsPerSet?: number;
  deuceEnabled?: boolean;
}

// Schedule Views
export type ScheduleView = 'timeslot' | 'court';

// Schedule
export interface ScheduleCandidate {
  solutionId: string;
  assignments: ScheduleAssignment[];
  objectiveScore: number;
  foundAtSeconds: number;
}

export interface ScheduleDTO {
  assignments: ScheduleAssignment[];
  unscheduledMatches: string[];
  softViolations: SoftViolation[];
  objectiveScore: number | null;
  infeasibleReasons: string[];
  status: 'optimal' | 'feasible' | 'infeasible' | 'unknown';
  /** Random seed the solver used. Pair with the Reproducible-run
   *  toggle to regenerate a byte-identical schedule. */
  solverSeed?: number;
  /** Top-N near-optimal alternatives the solver found while
   *  improving. ``assignments`` above mirrors
   *  ``candidates[activeCandidateIndex].assignments`` when set;
   *  callers should read via ``getActiveAssignments(schedule)`` to
   *  honour the active selection without crashing on legacy
   *  schedules where these fields are missing. */
  candidates?: ScheduleCandidate[];
  activeCandidateIndex?: number;
}

export interface ScheduleAssignment {
  matchId: string;
  slotId: number;
  courtId: number;
  durationSlots: number;
}

export interface SoftViolation {
  type: string;
  matchId?: string | null;
  playerId?: string | null;
  description: string;
  penaltyIncurred: number;
}

// Set score for badminton matches
export interface SetScore {
  sideA: number;
  sideB: number;
}

// Delay reason options
export type DelayReason = 'player_not_present' | 'injury' | 'court_issue' | 'other';

// Player confirmation entry for tracking who caused a delay
export interface PlayerDelayEntry {
  matchId: string;
  playerId: string;
  reason: DelayReason;
  timestamp: string;
}

// Match State (for Match Desk operations)
export interface MatchStateDTO {
  matchId: string;
  status: 'scheduled' | 'called' | 'started' | 'finished';
  /** ISO-8601 UTC timestamp, e.g. "2026-04-19T18:05:37.000Z".
   *  Set the first time a match transitions to `called`. Used to show
   *  "Called Xm ago" and as an audit point in the match details. */
  calledAt?: string;
  /** ISO-8601 UTC timestamp, e.g. "2026-04-19T18:05:37.000Z".
   *  Parsed via `parseMatchStartMs` on both live-ops and TV readers.
   *  Legacy "HH:MM" values are tolerated for one release cycle. */
  actualStartTime?: string;
  /** ISO-8601 UTC timestamp — see `actualStartTime`. */
  actualEndTime?: string;
  actualCourtId?: number; // Override court if different from scheduled
  originalSlotId?: number; // Original scheduled slot before being pushed
  originalCourtId?: number; // Original scheduled court before being pushed
  delayed?: boolean; // Explicitly marked as delayed
  delayReason?: DelayReason; // Reason for delay
  delayedPlayerId?: string; // Which player caused the delay (for tracking)
  postponed?: boolean; // Match is postponed to later
  pinned?: boolean; // Pinned to court/time (for finals/special matches)
  playerConfirmations?: Record<string, boolean>; // Player ID -> confirmed at court
  score?: {
    sideA: number;
    sideB: number;
  };
  sets?: SetScore[]; // For badminton set-by-set scoring
  notes?: string;
  updatedAt?: string;
}

export interface LiveScheduleState {
  currentTime: string;
  matchStates: Record<string, MatchStateDTO>;
  lastSynced: string;
}

// Roster Group (for school grouping)
export interface RosterGroupDTO {
  id: string;
  name: string;
  type?: 'group' | 'roster';
  parentId?: string | null;
  children?: string[]; // child group IDs
  playerIds?: string[]; // player IDs (for roster type)
  metadata?: {
    description?: string;
    color?: string;
    [key: string]: any;
  };
}

// Withdrawal reason
export type WithdrawalReason = 'injury' | 'no_show' | 'disqualification' | 'personal' | 'other';

// Player
export interface PlayerDTO {
  id: string; // Auto-generated UUID
  name: string;
  groupId: string; // School group ID (REQUIRED - this is school vs school scheduling)
  ranks?: string[]; // [MS1, MD1, XD1] - Player can play multiple events
  availability: AvailabilityWindow[];
  minRestMinutes?: number | null; // If not provided, uses tournament config's defaultRestMinutes
  notes?: string;
  status?: 'active' | 'withdrawn'; // Player status - defaults to 'active'
  withdrawalReason?: WithdrawalReason; // Reason if withdrawn
  withdrawnAt?: string; // Timestamp when withdrawn
}

export interface AvailabilityWindow {
  start: string; // HH:mm format
  end: string; // HH:mm format
}

export interface RosterImportDTO {
  csv: string; // CSV content
}

// Match Type - used for UI selection mode and match categorization
export type MatchType = 'individual' | 'roster_vs_roster' | 'roster_match' | 'auto_generated';

// Match Generation Rule
export interface MatchGenerationRule {
  type: 'all_vs_all' | 'round_robin' | 'bracket' | 'custom';
  rosterAId: string;
  rosterBId?: string;
  playersPerSide: number;
  constraints?: {
    avoidSameGroup?: boolean;
    maxMatchesPerPlayer?: number;
  };
}

// Match - simplified for school sparring (supports dual and tri-meets)
export interface MatchDTO {
  id: string;
  matchNumber?: number; // Auto-assigned sequential number for display (M1, M2, etc.)
  sideA: string[]; // Player IDs (School A)
  sideB: string[]; // Player IDs (School B)
  sideC?: string[]; // Player IDs (School C) - for tri-meets
  matchType?: 'dual' | 'tri'; // Match type
  eventRank?: string | null; // MS1, MS2, WS1, WS2, etc. - the rank/event this match represents
  eventCode?: string; // Event code like 'MS1', 'WD2' etc.
  durationSlots: number;
  preferredCourt?: number | null;
  tags?: string[]; // Optional tags like ['School A', 'School B']
}

export interface MatchesImportDTO {
  csv: string; // CSV content
}

// Tournament Export/Import (Complete tournament data - v2.0 format)
export interface TournamentExportV2 {
  version: '2.0';
  exportedAt: string; // ISO timestamp
  config: TournamentConfig;
  players: PlayerDTO[];
  matches: MatchDTO[];
  schedule?: ScheduleDTO;
  matchStates?: Record<string, MatchStateDTO>;
}

// Verbose message from solver
export interface SolverProgressMessage {
  type: 'progress';
  text: string;
}

// Solver Progress (for real-time optimization visualization)
export interface SolverProgressEvent {
  elapsed_ms: number;
  current_objective?: number;
  best_bound?: number;
  solution_count?: number;
  current_assignments?: ScheduleAssignment[];
  gap_percent?: number;
  messages?: SolverProgressMessage[];
}

// SSE "model_built" event — emitted once after CP-SAT model construction completes.
export interface SolverModelBuiltEvent {
  numMatches: number;
  numPlayers: number;
  numIntervals: number;
  numNoOverlap: number;
  numVariables: number;
  multiMatchPlayers?: number;
  totalSlots?: number;
  courtCount?: number;
}

// SSE "phase" event — emitted on solver phase transitions.
export type SolverPhaseName = 'presolve' | 'search' | 'proving';
export interface SolverPhaseEvent {
  phase: SolverPhaseName;
}

// Drag-to-reschedule types matching /schedule/validate.
export interface ProposedMove {
  matchId: string;
  slotId: number;
  courtId: number;
}

export interface ValidationConflictDTO {
  type: string;
  description: string;
  matchId?: string;
  otherMatchId?: string;
  playerId?: string;
  courtId?: number;
  slotId?: number;
}

export interface ValidationResponseDTO {
  feasible: boolean;
  conflicts: ValidationConflictDTO[];
}

// Whole-tournament persistence DTO (server-side JSON file at data/tournament.json).
export interface TournamentStateDTO {
  version: number;
  updatedAt?: string | null;
  config: TournamentConfig | null;
  groups: RosterGroupDTO[];
  players: PlayerDTO[];
  matches: MatchDTO[];
  schedule: ScheduleDTO | null;
  scheduleStats?: unknown;
  scheduleIsStale: boolean;
  /** Set only when the backend auto-restored a corrupted file from backup. */
  recoveredFromBackup?: string;
  /** Schema v2: monotonic counter bumped on every committed schedule change. */
  scheduleVersion?: number;
  /** Schema v2: rolling history of replaced committed schedules (capped server-side at 5). */
  scheduleHistory?: ScheduleHistoryEntry[];
}

// ---- Proposal pipeline (two-phase commit) -------------------------------

export interface ScheduleHistoryEntry {
  version: number;
  committedAt: string;
  trigger?: 'warm_restart' | 'repair' | 'manual_edit' | 'director_action' | 'initial' | string | null;
  summary?: string | null;
  schedule?: ScheduleDTO | null;
}

export interface MatchMove {
  matchId: string;
  fromSlotId?: number | null;
  toSlotId?: number | null;
  fromCourtId?: number | null;
  toCourtId?: number | null;
  matchNumber?: number | null;
  eventRank?: string | null;
}

export interface PlayerImpact {
  playerId: string;
  playerName?: string | null;
  matchCount: number;
  earliestSlotDelta: number;
}

export interface SchoolImpact {
  groupId: string;
  groupName?: string | null;
  matchCount: number;
}

export interface MetricDelta {
  objectiveDelta?: number | null;
  softViolationCountDelta: number;
  restViolationsDelta: number;
  proximityViolationsDelta: number;
  totalPenaltyDelta: number;
  unscheduledMatchesDelta: number;
}

export interface Impact {
  movedMatches: MatchMove[];
  affectedPlayers: PlayerImpact[];
  affectedSchools: SchoolImpact[];
  metricDelta: MetricDelta;
  infeasibilityWarnings: string[];
  clockShiftMinutesDelta: number;
}

export type ProposalKind = 'warm_restart' | 'repair' | 'manual_edit' | 'director_action';

export interface Proposal {
  id: string;
  kind: ProposalKind;
  proposedSchedule: ScheduleDTO;
  proposedConfig?: TournamentConfig | null;
  impact: Impact;
  summary?: string | null;
  fromScheduleVersion: number;
  createdAt: string;
  expiresAt: string;
}

// ---- Advisories (live operations) --------------------------------------

export type AdvisoryKind =
  | 'overrun'
  | 'no_show'
  | 'running_behind'
  | 'infeasibility_risk'
  | 'start_delay_detected'
  | 'approaching_blackout';

export type AdvisorySeverity = 'info' | 'warn' | 'critical';

export interface SuggestedAction {
  kind: 'warm_restart' | 'repair' | 'delay_start' | 'insert_blackout' | 'compress_remaining' | 'remove_blackout';
  payload: Record<string, unknown>;
}

export interface Advisory {
  id: string;
  kind: AdvisoryKind;
  severity: AdvisorySeverity;
  summary: string;
  detail?: string | null;
  matchId?: string | null;
  courtId?: number | null;
  suggestedAction?: SuggestedAction | null;
  /** Set when the worker has stamped a pre-baked Suggestion for this
   *  advisory; the frontend treats this as "Apply available" instead
   *  of "Review" — one-click commits the underlying proposal. */
  suggestionId?: string | null;
  detectedAt: string;
}

/** Pre-computed re-optimization proposal surfaced in the inbox.
 *  Wraps a still-live Proposal with display copy + dedup fingerprint.
 *  The frontend reads these from GET /schedule/suggestions; Apply
 *  commits the underlying proposal, Dismiss cancels it. */
export interface Suggestion {
  id: string;
  kind: 'repair' | 'optimize' | 'director' | 'candidate';
  title: string;
  metric: string;
  proposalId: string;
  fingerprint: string;
  fromScheduleVersion: number;
  createdAt: string;
  expiresAt: string;
}

export interface BackupEntryDTO {
  filename: string;
  sizeBytes: number;
  modifiedAt: string;
}

export interface BackupListDTO {
  backups: BackupEntryDTO[];
}

export interface BackupCreatedDTO {
  created: boolean;
  filename: string | null;
}

// Multi-tournament CRUD (Step 2; widened in Step 6)
export type TournamentStatus = 'draft' | 'active' | 'archived';

export type TournamentRole = 'owner' | 'operator' | 'viewer';

export interface TournamentSummaryDTO {
  id: string;
  name: string | null;
  status: TournamentStatus;
  tournamentDate: string | null;
  createdAt: string;
  updatedAt: string;
  /** Caller's role on this tournament — non-null in list responses
   *  because the list is filtered to the caller's memberships. */
  role: TournamentRole | null;
  /** Owner's email, denormalised at tournament-create time. Used by
   *  the "Shared with You" dashboard section. */
  ownerName: string | null;
}

export interface TournamentCreateDTO {
  name?: string | null;
  tournamentDate?: string | null;
}

export interface TournamentUpdateDTO {
  name?: string | null;
  status?: TournamentStatus;
  tournamentDate?: string | null;
}

// Invite links (Step 7)
export type InviteRole = 'operator' | 'viewer';

export interface InviteCreateDTO {
  role: InviteRole;
}

export interface InviteCreatedDTO {
  token: string;
  /** Relative path — frontend prepends ``window.location.origin``. */
  url: string;
  tournamentId: string;
  role: InviteRole;
  createdAt: string;
}

export interface InviteSummaryDTO {
  token: string;
  tournamentId: string;
  role: InviteRole;
  createdAt: string;
  expiresAt: string | null;
  revokedAt: string | null;
  valid: boolean;
}

export interface InviteResolveDTO {
  token: string;
  tournamentId: string;
  tournamentName: string | null;
  role: InviteRole;
  valid: boolean;
  expiresAt: string | null;
  revokedAt: string | null;
}

export interface InviteAcceptedDTO {
  tournamentId: string;
  role: string;
  alreadyMember: boolean;
}

export interface TournamentMemberDTO {
  userId: string;
  role: string;
  joinedAt: string;
}

// ---- Operator commands (Step F of the architecture-adjustment arc) -------

export type MatchAction =
  | 'call_to_court'
  | 'start_match'
  | 'finish_match'
  | 'retire_match'
  | 'uncall';

/**
 * Body of ``POST /tournaments/{tid}/commands``. The ``id`` is the
 * client-generated UUID used as the idempotency key; the same id
 * resubmitted gets the original outcome.
 */
export interface CommandRequestDTO {
  id: string;
  match_id: string;
  action: MatchAction;
  payload: Record<string, unknown> | null;
  seen_version: number;
}

/**
 * Successful (200) response body — carries the *current* match
 * state. Replay after a third-party update returns the current
 * (mutated) state, not the post-original-apply state.
 */
export interface CommandResponseDTO {
  command_id: string;
  match_id: string;
  status: 'scheduled' | 'called' | 'playing' | 'finished' | 'retired';
  version: number;
  court_id: number | null;
  time_slot: number | null;
  applied_at: string;
  replay: boolean;
}

/**
 * Body shape for 409 (state-machine conflict or stale version).
 * ``error`` discriminates between the two flavours; the frontend
 * branches on it to choose between "refetch and retry" and "show
 * permanent rejection."
 */
export interface CommandConflictDTO {
  error: 'conflict' | 'stale_version';
  match_id: string;
  message: string;
  current_status?: string;
  attempted_status?: string;
  current_version?: number;
  attempted_version?: number;
}

// Constraint Visualization Types
export interface ConstraintViolation {
  type: 'rest' | 'overlap' | 'availability' | 'court_capacity' | 'game_proximity_min' | 'game_proximity_max';
  severity: 'hard' | 'soft';
  playerIds: string[];
  matchIds: string[];
  description: string;
}

export interface GraphNode {
  id: string;
  name: string;
  groupId: string;
  matchCount: number;
  x?: number;
  y?: number;
}

export interface GraphEdge {
  source: string;
  target: string;
  matchId: string;
  status: 'conflict' | 'resolved' | 'soft_violation';
}

export interface GraphData {
  nodes: GraphNode[];
  links: GraphEdge[];
}

