/**
 * Data Transfer Objects (DTOs).
 *
 * Contract types here mirror Pydantic models in
 * ``apps/api/src/core/schemas.py``. The auto-generated ``dto.generated.ts``
 * (produced by ``make generate-api`` from FastAPI's OpenAPI schema) is
 * the authoritative reference — when schemas.py changes, regenerate
 * dto.generated.ts and reconcile every drift in this file by hand.
 *
 * Frontend-private types (SSE event shapes, internal enums, importer
 * payloads, view discriminators) intentionally do NOT live in the
 * OpenAPI schema and are hand-written here.
 *
 * DO NOT EDIT THIS FILE WITHOUT VERIFYING IT MATCHES dto.generated.ts.
 * Two shapes no longer need that verification because they ARE the
 * generated type: `MeetStandingRowDTO` (here) and `StandingRowDTO`
 * (bracketDto.ts).
 */

// SP-DM-3 P1: the two standings row shapes are taken from the generated
// OpenAPI types rather than hand-mirrored (R-DM-9(c), applied to the shapes
// whose divergence count is already zero). A generated alias cannot drift, so
// these two need no parity entry - see api/__tests__/dtoParity.test.ts.
import type { components } from './dto.generated';

// Tournament Configuration
export interface TournamentConfig {
  // Human-readable name. Used as a slug in backup filenames and as
  // the headline on the public TV display. Optional — when unset,
  // chrome falls back to "Tournament" / "tournament-<timestamp>".
  tournamentName?: string;
  // Per-tournament meet mode.
  //
  //   ``dual`` — exactly two schools play each other. The default.
  //   ``tri``  — three schools, full round-robin: every pair (A-B,
  //              A-C, B-C) plays each event TWICE so combined results
  //              decide the meet. Every individual match is still A
  //              vs B (one side per side, like dual) — there is no
  //              such thing as a "1v1v1" match in badminton.
  //
  // The auto-match generator branches on this; rendering surfaces
  // do not (matches always render as A vs B regardless of mode).
  meetMode?: 'dual' | 'tri';
  intervalMinutes: number;
  dayStart: string; // HH:mm format
  dayEnd: string; // HH:mm format
  tournamentDate?: string; // ISO date string: "2026-02-15"
  breaks: BreakWindow[];
  courtCount: number;
  defaultRestMinutes: number;
  freezeHorizonSlots: number;
  rankCounts?: Record<string, number>; // {"MS": 3, "WS": 3, "MD": 2, "WD": 4, "XD": 2}
  enableCourtUtilization?: boolean;
  courtUtilizationPenalty?: number;
  // Game proximity constraint
  enableGameProximity?: boolean;
  minGameSpacingSlots?: number | null;
  maxGameSpacingSlots?: number | null;
  gameProximityPenalty?: number;
  // Compact schedule - minimize makespan or eliminate gaps
  enableCompactSchedule?: boolean;
  compactScheduleMode?: 'minimize_makespan' | 'no_gaps' | 'finish_by_time';
  compactSchedulePenalty?: number;
  targetFinishSlot?: number | null;
  // Allow player overlap
  allowPlayerOverlap?: boolean;
  playerOverlapPenalty?: number;
  // Scoring format for badminton
  scoringFormat?: 'simple' | 'badminton';
  setsToWin?: number; // 1 (best of 1), 2 (best of 3), or 3 (best of 5)
  pointsPerSet?: number; // 11, 15, or 21
  deuceEnabled?: boolean; // Win by 2 in deuce (up to 30 for 21-point sets)
  // ---- Public TV display ------------------------------------------
  // How the public ``/display`` page renders the courts view.
  //
  //   strip — one tall row per court (default; best 3-6 courts, 1080p).
  //   grid  — 2-column responsive grid (best 8-16 courts).
  //   list  — dense one-line rows (best 16+ courts, side display).
  /** 'strip' is retired but still accepted from stored blobs — the board
   *  maps it to 'auto' on read (DC-1). New writes never send it. */
  tvDisplayMode?: 'auto' | 'strip' | 'grid' | 'list';
  // Brand accent for the public display — hex (``#RRGGBB``). Drives
  // the LIVE border, the LIVE pill, and the progress bar. Defaults to
  // emerald (``#10b981``) when unset.
  tvAccent?: string;
  // Display preset id — selects the substrate palette (bg/text/border)
  // for the public ``/display`` page. See displayPresets.ts for the
  // full list (court, pitch, midnight, ash, paper, chalk, daylight,
  // sand). Defaults to ``court`` when unset.
  tvPreset?: string;
  // Force a specific column count for grid mode. ``null`` / unset =
  // auto (1-2 columns based on viewport).
  tvGridColumns?: 1 | 2 | 3 | 4 | null;
  // Card size — overrides the auto-sizing strip/grid layouts.
  // ``auto`` keeps the current behaviour; ``compact`` shrinks padding;
  // ``comfortable`` is the default tall card; ``large`` expands for
  // big-room viewing.
  tvCardSize?: 'auto' | 'compact' | 'comfortable' | 'large';
  // Whether to show the live score on the public display. Off when
  // the venue prefers to keep scores private until the match ends.
  tvShowScores?: boolean;
  // Display layout configuration (UI-only; all optional).
  courtOrder?: number[] | null;
  hiddenCourts?: number[] | null;
  standingsMode?: 'off' | 'side' | 'rotate' | null;
  /** Board rotation (TV-7 / DC-3). `null` = every slide that has data.
   *  'side' and 'rotate' on standingsMode are equivalent now — the side
   *  panel is retired — and only 'off' still changes anything. */
  tvRotationSlides?: ('courts' | 'standings' | 'upNext')[] | null;
  tvRotationDwellSeconds?: number | null;
  // Optional event-column ordering and visibility for the Roster
  // position grid. Defaults to the canonical MD / WD / XD / WS / MS
  // sequence. Hidden columns are stored as ``false`` per rank.
  eventOrder?: string[];
  eventVisible?: Record<string, boolean>;
  // ---- Engine settings -------------------------------------------
  // Reproducible-run mode: solver runs single-threaded with a fixed
  // seed so the same input produces a byte-identical schedule across
  // runs. ~3× slower than parallel mode; default off.
  deterministic?: boolean;
  // Seed used in deterministic mode. Default 42 when unset.
  randomSeed?: number;
  // Solver wall-clock cap. The CP-SAT solver returns the best
  // feasible schedule found within this window. Higher = closer to
  // optimal at the cost of operator wait time. Default 30 s.
  solverTimeLimitSeconds?: number;
  // Director time-axis: minutes added to every unstarted match's
  // displayed wall-clock by `delay_start` actions. Solver still plans
  // on the abstract slot grid; this is purely a display offset.
  clockShiftMinutes?: number;
  // Court IDs (1-indexed) closed *all day* — the legacy shape kept
  // for backward compat with persisted state. New time-bounded
  // closures go into ``courtClosures`` below.
  closedCourts?: number[];
  // Time-bounded court closures. Each entry forbids the named
  // court inside its half-open ``[fromTime, toTime)`` window. Either
  // bound omitted means open-ended on that side; both omitted is
  // equivalent to a legacy ``closedCourts`` entry (full-day).
  courtClosures?: CourtClosure[];
  // Court policy (SP-COURT-1, ADR 0015). "pinned" (default) = the solver
  // promises a specific court per match; "queue" = the solver pools the
  // courts and solves for time only, courts assigned by colouring — how a
  // real desk runs the day. Per-court overrides let a show court stay
  // pinned inside a queue-mode venue. Keys are 1-indexed court ids.
  courtPolicy?: 'pinned' | 'queue';
  courtOverrides?: Record<number, 'pinned' | 'pool'>;
  // How many "on deck" matches the Run desk highlights (CP5, 1-5).
  // Default 3 — research says call the next 2-3 about ten minutes early.
  onDeckCount?: number;
  // How many near-optimal alternative schedules the solver keeps
  // alongside the chosen one. Operator can swap to a candidate in a
  // click when reality (overrun, withdrawal, court closure) makes
  // the chosen plan no longer fit — no re-solve needed. Default 5.
  candidatePoolSize?: number;
  /** Slots of forced rest between bracket rounds. Bracket-side only. */
  restBetweenRounds?: number;
}

export interface CourtClosure {
  courtId: number;
  /** HH:mm; omit for "from start of day". */
  fromTime?: string;
  /** HH:mm; omit for "until end of day". */
  toTime?: string;
  reason?: string;
}

export interface BreakWindow {
  start: string; // HH:mm format
  end: string; // HH:mm format
}

// Schedule Views
export type ScheduleView = 'timeslot' | 'court';

// Schedule
export interface ScheduleCandidate {
  solutionId: string;
  assignments: ScheduleAssignment[];
  objectiveScore: number;
  foundAtSeconds: number;
}

export interface ScheduleDTO {
  assignments: ScheduleAssignment[];
  unscheduledMatches: string[];
  softViolations: SoftViolation[];
  objectiveScore: number | null;
  infeasibleReasons: string[];
  status: 'optimal' | 'feasible' | 'infeasible' | 'unknown';
  /** Random seed the solver used. Pair with the Reproducible-run
   *  toggle to regenerate a byte-identical schedule. */
  solverSeed?: number;
  /** What the engine actually did (SP-COURT-1 CP8-v1): a queue-mode solve
   *  with closed-court windows falls back to "pinned" and says so here, so
   *  the Plan board can explain the grid instead of showing a call list the
   *  solve did not produce. Absent on pre-policy schedules = pinned. */
  effectivePolicy?: 'pinned' | 'queue';
  /** Top-N near-optimal alternatives the solver found while
   *  improving. ``assignments`` above mirrors
   *  ``candidates[activeCandidateIndex].assignments`` when set;
   *  callers should read via ``getActiveAssignments(schedule)`` to
   *  honour the active selection without crashing on legacy
   *  schedules where these fields are missing. */
  candidates?: ScheduleCandidate[];
  activeCandidateIndex?: number;
}

export interface ScheduleAssignment {
  matchId: string;
  slotId: number;
  courtId: number;
  durationSlots: number;
}

export interface SoftViolation {
  type: string;
  matchId?: string | null;
  playerId?: string | null;
  description: string;
  penaltyIncurred: number;
}

// Set score for badminton matches
export interface SetScore {
  sideA: number;
  sideB: number;
}

// Delay reason options
type DelayReason = 'player_not_present' | 'injury' | 'court_issue' | 'other';

// Player confirmation entry for tracking who caused a delay
// Match State (for Match Desk operations)
export interface MatchStateDTO {
  matchId: string;
  status: 'scheduled' | 'called' | 'started' | 'finished';
  /** ISO-8601 UTC timestamp, e.g. "2026-04-19T18:05:37.000Z".
   *  Set the first time a match transitions to `called`. Used to show
   *  "Called Xm ago" and as an audit point in the match details. */
  calledAt?: string;
  /** ISO-8601 UTC timestamp, e.g. "2026-04-19T18:05:37.000Z".
   *  Parsed via `parseMatchStartMs` on both live-ops and TV readers.
   *  Legacy "HH:MM" values are tolerated for one release cycle. */
  actualStartTime?: string;
  /** ISO-8601 UTC timestamp — see `actualStartTime`. */
  actualEndTime?: string;
  actualCourtId?: number; // Override court if different from scheduled
  actualSlotId?: number; // Live slot override (set from command response time_slot)
  originalSlotId?: number; // Original scheduled slot before being pushed
  originalCourtId?: number; // Original scheduled court before being pushed
  delayed?: boolean; // Explicitly marked as delayed
  delayReason?: DelayReason; // Reason for delay
  delayedPlayerId?: string; // Which player caused the delay (for tracking)
  postponed?: boolean; // Match is postponed to later
  pinned?: boolean; // Pinned to court/time (for finals/special matches)
  playerConfirmations?: Record<string, boolean>; // Player ID -> confirmed at court
  score?: {
    sideA: number;
    sideB: number;
  };
  sets?: SetScore[]; // For badminton set-by-set scoring
  notes?: string;
  updatedAt?: string;
}

// Roster Group (for school grouping)
export interface RosterGroupDTO {
  id: string;
  name: string;
  type?: 'group' | 'roster';
  parentId?: string | null;
  children?: string[]; // child group IDs
  playerIds?: string[]; // player IDs (for roster type)
  metadata?: {
    description?: string;
    color?: string;
    [key: string]: any;
  };
}

// Withdrawal reason
type WithdrawalReason = 'injury' | 'no_show' | 'disqualification' | 'personal' | 'other';

// Player
export interface PlayerDTO {
  id: string; // Auto-generated UUID
  name: string;
  groupId: string; // School group ID (REQUIRED - this is school vs school scheduling)
  ranks?: string[]; // [MS1, MD1, XD1] - Player can play multiple events
  availability: AvailabilityWindow[];
  minRestMinutes?: number | null; // If not provided, uses tournament config's defaultRestMinutes
  notes?: string;
  status?: 'active' | 'withdrawn'; // Player status - defaults to 'active'
  withdrawalReason?: WithdrawalReason; // Reason if withdrawn
  withdrawnAt?: string; // Timestamp when withdrawn
  /** Entries provenance (SP-E1-1, spec §5 Seam A) — the `entries.id` this
   *  player was materialized from. Half of the seam's back-reference pair
   *  (`entries.committed_player_id` is the other half). Declared here because
   *  the backend `PlayerDTO` is a StrictModel: an undeclared key is REFUSED
   *  (422), so the autosave PUT must carry the field by name or the whole
   *  blob write fails once a committed player is in the roster. */
  sourceEntryId?: string;
  /** R-DM-2(a) — the person key. `sourceEntryId` points at ONE entry; this
   *  points at the HUMAN, who routinely holds several. Same value the
   *  `entry-{uuid}` id encodes, typed instead of parsed out of a prefix.
   *  Declared here for the same StrictModel reason as `sourceEntryId`. */
  entryPlayerId?: string;
  /** Other confirmed Meet doubles partners, keyed by bare division. */
  partnerPlayerIds?: Record<string, string>;
  /** The entrant's own free-text availability sentence, carried verbatim from
   *  `entries.remarks`. Deliberately NOT `notes` — that is the operator's own
   *  field, and overwriting it would destroy what the operator wrote and lose
   *  the attribution. Never parsed, never fed to the solver. */
  remarks?: string;
}

export interface AvailabilityWindow {
  start: string; // HH:mm format
  end: string; // HH:mm format
}

/** Roster entry for bracket-kind tournaments. */
export interface BracketPlayerDTO {
  id: string;
  name: string;
  notes?: string;
  /** Per-player rest override in slots; unset = session `defaultRestSlots`. */
  restSlots?: number;
  /** POSITIVE (allowed) HH:mm windows — empty/unset means available all
   *  day. Mirrors the backend `BracketPlayerDTO.availability` (SP-D7 S2),
   *  which threads it into the CP-SAT solve via player_constraints. */
  availability?: AvailabilityWindow[];
  /** Entries provenance — mirrors `PlayerDTO`. The Bracket half of Seam A
   *  writes the `bracket_participants` row *and* this blob entry, because the
   *  participant table has nowhere to put a remark. */
  sourceEntryId?: string;
  /** R-DM-2(a) — the person key, mirroring `PlayerDTO`. Also stored as
   *  `bracket_participants.entry_player_id`; this blob copy is what the
   *  roster/availability surfaces read. */
  entryPlayerId?: string;
  remarks?: string;
}

// Match Type - used for UI selection mode and match categorization
// Match Generation Rule
// Match - simplified for school sparring (supports dual and tri-meets)
export interface MatchDTO {
  id: string;
  matchNumber?: number; // Auto-assigned sequential number for display (M1, M2, etc.)
  sideA: string[]; // Player IDs (School A)
  sideB: string[]; // Player IDs (School B)
  sideC?: string[]; // Player IDs (School C) - for tri-meets
  matchType?: 'dual' | 'tri'; // Match type
  eventRank?: string | null; // MS1, MS2, WS1, WS2, etc. - the rank/event this match represents
  eventCode?: string; // Event code like 'MS1', 'WD2' etc.
  durationSlots: number;
  preferredCourt?: number | null;
  tags?: string[]; // Optional tags like ['School A', 'School B']
}

/** Server-generated Meet lineup preview. Custom matches from the posted
 * state are returned alongside freshly generated lineup matches. */
export interface LineupDTO {
  matches: MatchDTO[];
  incompletePairs: string[];
}

// Tournament Export/Import (Complete tournament data - v2.0 format)
// Verbose message from solver
interface SolverProgressMessage {
  type: 'progress';
  text: string;
}

// Solver Progress (for real-time optimization visualization)
export interface SolverProgressEvent {
  elapsed_ms: number;
  current_objective?: number;
  best_bound?: number;
  solution_count?: number;
  current_assignments?: ScheduleAssignment[];
  gap_percent?: number;
  messages?: SolverProgressMessage[];
}

// SSE "model_built" event — emitted once after CP-SAT model construction completes.
export interface SolverModelBuiltEvent {
  numMatches: number;
  numPlayers: number;
  numIntervals: number;
  numNoOverlap: number;
  numVariables: number;
  multiMatchPlayers?: number;
  totalSlots?: number;
  courtCount?: number;
}

// SSE "phase" event — emitted on solver phase transitions.
type SolverPhaseName = 'presolve' | 'search' | 'proving';
export interface SolverPhaseEvent {
  phase: SolverPhaseName;
}

// ---- Solve jobs (SP-CLOUD-1 async solve rail) --------------------------
// Mirrors apps/api/src/core/schemas.py SolveJobDTO / SolveJobErrorDTO.

export type SolveJobStatus =
  | 'queued'
  | 'claimed'
  | 'running'
  | 'succeeded'
  | 'failed'
  | 'infeasible'
  | 'cancelled';

export const SOLVE_JOB_TERMINAL_STATUSES: ReadonlySet<SolveJobStatus> = new Set([
  'succeeded',
  'failed',
  'infeasible',
  'cancelled',
]);

export interface SolveJobErrorDTO {
  code: string;
  message?: string;
  detail?: Record<string, unknown> | null;
}

export interface SolveJobDTO {
  id: string;
  tournamentId: string;
  type: string;
  status: SolveJobStatus;
  attempts: number;
  maxAttempts: number;
  /** Worker heartbeat metadata (best-effort; absent until first beat). */
  progress?: Record<string, unknown> | null;
  /** ScheduleDTO on succeeded AND on infeasible (its status field says which). */
  result?: ScheduleDTO | null;
  error?: SolveJobErrorDTO | null;
  /** Persisted solver params — reproducibility record. */
  params: Record<string, unknown>;
  createdAt: string;
  startedAt?: string | null;
  finishedAt?: string | null;
}

export interface SolveJobListDTO {
  jobs: SolveJobDTO[];
}

// Drag-to-reschedule types matching /schedule/validate.
export interface ProposedMove {
  matchId: string;
  slotId: number;
  courtId: number;
}

interface ValidationConflictDTO {
  type: string;
  description: string;
  matchId?: string;
  otherMatchId?: string;
  playerId?: string;
  courtId?: number;
  slotId?: number;
}

export interface ValidationResponseDTO {
  feasible: boolean;
  conflicts: ValidationConflictDTO[];
}

/** One group's school-vs-school pool record. Computed fresh server-side on
 *  every `GET /tournaments/{id}/state` (see `services.meet.standings` on the
 *  backend) — never sent back on PUT, and any client-sent value is ignored
 *  (the backend strips it before persisting). Empty when the Meet module
 *  isn't enabled for the workspace or there's no finished, scored pool play
 *  yet. Replaces the client-side `groupScores` computation that used to
 *  live in MeetDisplayPage.tsx. */
export type MeetStandingRowDTO = components['schemas']['MeetStandingRowDTO'];

// Whole-tournament persistence DTO (server-side JSON file at data/tournament.json).
export interface TournamentStateDTO {
  version: number;
  updatedAt?: string | null;
  config: TournamentConfig | null;
  groups: RosterGroupDTO[];
  players: PlayerDTO[];
  matches: MatchDTO[];
  schedule: ScheduleDTO | null;
  scheduleStats?: unknown;
  scheduleIsStale: boolean;
  /** Set only when the backend auto-restored a corrupted file from backup. */
  recoveredFromBackup?: string;
  /** Schema v2: monotonic counter bumped on every committed schedule change. */
  scheduleVersion?: number;
  /** Schema v2: rolling history of replaced committed schedules (capped server-side at 5). */
  scheduleHistory?: ScheduleHistoryEntry[];
  /** Bracket-kind roster. Empty for meet-kind tournaments. */
  bracketPlayers?: BracketPlayerDTO[];
  /** Set true once the first-load reconcile from `bracket_participants` has run. */
  bracketRosterMigrated?: boolean;
  /** SP-G1: set true once the operations plan has been finalised by the director. */
  planFinalized?: boolean;
  /** Authoritative Meet pool standings (Display redesign, Task 2) — derived,
   *  read-only. Absent/empty for bracket-kind or Meet-disabled workspaces. */
  standings?: MeetStandingRowDTO[];
}

// Canonical workflow-first Setup facade. These types intentionally mirror the
// section-oriented API rather than leaking the legacy state-blob shape into
// the Setup product. Section data is open because each section has a distinct
// validated schema on the API, while the envelope and issue vocabulary stay
// stable for task-list rendering.
export type SetupKey =
  | 'general'
  | 'dates'
  | 'venue'
  | 'events'
  | 'rules'
  | 'entries'
  | 'people'
  | 'public-info';

export type SetupStatus =
  | 'not_started'
  | 'in_progress'
  | 'ready'
  | 'blocked'
  | 'published'
  | 'complete';

export interface SetupIssueDTO {
  code: string;
  severity: 'info' | 'warning' | 'blocking';
  message: string;
  path?: string | null;
}

export type SetupSectionData = Record<string, unknown>;

export interface SetupSectionStateDTO {
  key: SetupKey;
  status: SetupStatus;
  summary: string;
  data: SetupSectionData;
  issues: SetupIssueDTO[];
  downstreamImpact: string[];
  updatedAt?: string | null;
  /** Who owns this section's truth (SP-OPCON-1 ruling R-N A): `domain` =
   * derived from real rows, read-only here — edit on the owning surface. */
  authority: 'setup' | 'domain';
}

export interface TournamentSetupDTO {
  tournamentId: string;
  status: SetupStatus;
  blockingIssueCount: number;
  sections: SetupSectionStateDTO[];
}

export interface TournamentActivityEntryDTO {
  id: string;
  occurredAt: string;
  actorId: string;
  actorName: string;
  action: string;
  target: string;
  summary: string;
}

export interface TournamentActivityFeedDTO {
  entries: TournamentActivityEntryDTO[];
}

// ---- Proposal pipeline (two-phase commit) -------------------------------

export interface ScheduleHistoryEntry {
  version: number;
  committedAt: string;
  trigger?: 'warm_restart' | 'repair' | 'manual_edit' | 'director_action' | 'initial' | string | null;
  summary?: string | null;
  schedule?: ScheduleDTO | null;
}

export interface MatchMove {
  matchId: string;
  fromSlotId?: number | null;
  toSlotId?: number | null;
  fromCourtId?: number | null;
  toCourtId?: number | null;
  matchNumber?: number | null;
  eventRank?: string | null;
}

export interface PlayerImpact {
  playerId: string;
  playerName?: string | null;
  matchCount: number;
  earliestSlotDelta: number;
}

export interface SchoolImpact {
  groupId: string;
  groupName?: string | null;
  matchCount: number;
}

export interface MetricDelta {
  objectiveDelta?: number | null;
  softViolationCountDelta: number;
  restViolationsDelta: number;
  proximityViolationsDelta: number;
  totalPenaltyDelta: number;
  unscheduledMatchesDelta: number;
}

export interface Impact {
  movedMatches: MatchMove[];
  affectedPlayers: PlayerImpact[];
  affectedSchools: SchoolImpact[];
  metricDelta: MetricDelta;
  infeasibilityWarnings: string[];
  clockShiftMinutesDelta: number;
}

export type ProposalKind = 'warm_restart' | 'repair' | 'manual_edit' | 'director_action';

export interface Proposal {
  id: string;
  kind: ProposalKind;
  proposedSchedule: ScheduleDTO;
  proposedConfig?: TournamentConfig | null;
  impact: Impact;
  summary?: string | null;
  fromScheduleVersion: number;
  createdAt: string;
  expiresAt: string;
}

// ---- Advisories (live operations) --------------------------------------

type AdvisoryKind =
  | 'overrun'
  | 'no_show'
  | 'running_behind'
  | 'infeasibility_risk'
  | 'start_delay_detected'
  | 'approaching_blackout';

export type AdvisorySeverity = 'info' | 'warn' | 'critical';

export interface SuggestedAction {
  kind: 'warm_restart' | 'repair' | 'delay_start' | 'insert_blackout' | 'compress_remaining' | 'remove_blackout';
  payload: Record<string, unknown>;
}

export interface Advisory {
  id: string;
  kind: AdvisoryKind;
  severity: AdvisorySeverity;
  summary: string;
  detail?: string | null;
  matchId?: string | null;
  courtId?: number | null;
  suggestedAction?: SuggestedAction | null;
  /** Set when the worker has stamped a pre-baked Suggestion for this
   *  advisory; the frontend treats this as "Apply available" instead
   *  of "Review" — one-click commits the underlying proposal. */
  suggestionId?: string | null;
  detectedAt: string;
}

/** Pre-computed re-optimization proposal surfaced in the inbox.
 *  Wraps a still-live Proposal with display copy + dedup fingerprint.
 *  The frontend reads these from GET /schedule/suggestions; Apply
 *  commits the underlying proposal, Dismiss cancels it. */
export interface Suggestion {
  id: string;
  kind: 'repair' | 'optimize' | 'director' | 'candidate';
  title: string;
  metric: string;
  proposalId: string;
  fingerprint: string;
  fromScheduleVersion: number;
  createdAt: string;
  expiresAt: string;
}

export interface BackupEntryDTO {
  filename: string;
  sizeBytes: number;
  modifiedAt: string;
  /** `auto` (a state write snapshotted the prior payload) or `manual` (the
   *  director asked for it). Only auto rows rotate (WSB-3), so the list says
   *  which is which. Optional for older payloads. */
  origin?: 'auto' | 'manual';
}

export interface BackupListDTO {
  backups: BackupEntryDTO[];
}

export interface AuthorityStatusDTO {
  tournament_id: string;
  node_id: string;
  authority_epoch: number;
  state: 'preparing' | 'active' | 'closed' | 'recovered';
  checkpoint_hash: string;
  highest_contiguous_sequence: number;
  pending_operations: number;
  oldest_pending_at: string | null;
  blocked_operations: number;
  last_blocked_error_code: string | null;
}

/** Evidence retained when an event-node operation cannot be safely applied.
 * The rejected envelope is immutable; resolving it appends a correction
 * operation and only changes this record's audit state. */
export interface SyncQuarantineRecord {
  id: string;
  tournament_id: string;
  node_id?: string | null;
  authority_epoch?: number | null;
  operation_id?: string | null;
  reason_code: string;
  detail?: Record<string, unknown> | null;
  status: string;
  created_at: string;
  resolved_at?: string | null;
  resolved_by?: string | null;
  resolution_operation_id?: string | null;
  resolution_note?: string | null;
}

export interface SyncQuarantineListResponse {
  items: SyncQuarantineRecord[];
}

export interface SyncCorrectionCandidate {
  operation_id: string;
  sequence: number;
  command_type: string;
  aggregate_type: string;
  aggregate_id: string;
  accepted_at_node: string;
}

export interface SyncCorrectionCandidateListResponse {
  items: SyncCorrectionCandidate[];
}

export interface SyncQuarantineResolutionRequest {
  reason: string;
  correction_operation_id: string;
}

export interface BackupCreatedDTO {
  created: boolean;
  filename: string | null;
}

// Multi-tournament CRUD (Step 2; widened in Step 6)
export type TournamentStatus = 'draft' | 'active' | 'archived';

export type TournamentRole = 'owner' | 'operator' | 'viewer';

/** Top-level kind of event a tournament row represents. ``meet`` is
 *  the intercollegiate dual / tri-meet workflow (Setup / Roster /
 *  Matches / Schedule / Live / TV tabs); ``bracket`` is a single-
 *  elimination or round-robin draw (BracketTab surface only, meet
 *  tabs hidden). User-facing copy calls ``bracket`` a "Tournament";
 *  the wire-format keeps ``bracket`` for code symmetry with the
 *  bracket_* table family. */
type TournamentKind = 'meet' | 'bracket';

/** A persisted workspace module (from the backend `workspace_modules` table).
 *  Statuses: enabled | available | disabled | coming_soon. All modules are fully
 *  built, so `coming_soon` is legacy/defensive only — the frontend maps any such
 *  value to `available` in `modulesFromDto` (it never renders a "coming soon" state). */
export interface WorkspaceModuleDTO {
  /** `entries` is CLOUD-ONLY (SP-E1-1 ruling D2): the backend seeds and returns
   *  the row only when `AUTH_MODE=cloud`, so a local-mode workspace never sees
   *  it here. The union carries it because the wire can. */
  moduleId: 'meet' | 'bracket' | 'display' | 'entries';
  status: 'enabled' | 'available' | 'disabled' | 'coming_soon';
  config: Record<string, unknown> | null;
  /** Whether this module owns operational data (matches, draws). Disabling
   *  such a module 409s, and the catalog says so BEFORE the click (WSMOD-2).
   *  Server-computed; optional for older payloads. */
  hasData?: boolean;
}

// ---- Entries (SP-E1-1) ------------------------------------------------

/** The entry lifecycle vocabulary (spec §6). E1 only ever *produces*
 *  `pending` → `confirmed` (ruling D1 — submissions skip `unverified` until
 *  E2's email verification ships, and reject/promote/withdraw are E2), but the
 *  desk must render whatever the backend hands it, so the full set is typed. */
export type EntryState =
  | 'unverified'
  | 'pending'
  | 'confirmed'
  | 'rejected'
  | 'waitlisted'
  | 'withdrawn';

/** One row of the operator's entries desk — mirrors the backend
 *  `EntryDeskRowDTO`, which is a PROJECTION rather than the table: the
 *  doubles columns are deliberately absent, and so is every piece of
 *  entrant credential material. (This comment used to name
 *  `manage_token_hash` as the thing being withheld; ruling R10 deleted
 *  that column outright — managing an entry is login-gated "my entries"
 *  now, and the material to keep off this screen is the account's
 *  password hash and session token.)
 *
 *  There is no separate `flags` field on the wire. The R7 soft-duplicate
 *  signal is the `needs_review` member of `pendingReasons` — one list, one
 *  source of truth; a parallel flags array would be a second place for the
 *  same fact to disagree with itself. */
export interface EntryDTO {
  id: string;
  entryEventId: string;
  /** Denormalized from `entry_events.code` — the same string the commit seam
   *  turns into `ranks[]`. Null when the event row is missing. */
  eventCode: string | null;
  state: EntryState;
  /** Reason codes: `awaiting_partner` | `awaiting_payment` | `over_cap` |
   *  `needs_review` | `gender_mismatch`. The last is an ENTRY-level reason
   *  on the `needs_review` precedent (SP-E1-2 Phase A), deliberately not
   *  one of the workspace attention codes — a different vocabulary read by
   *  a different surface. */
  pendingReasons: string[];
  /** The act this entry arrived on (R13). `contactName` / `contactEmail`
   *  used to be fields on this row; they are one hop out now, because "who
   *  to write to about this" belongs to the submission and a desk that
   *  repeated it per entry showed one address three times for one form.
   *  Null only in the shape the type allows and the writer never
   *  produces — see the backend DTO. */
  submission: EntrySubmissionDTO | null;
  playerName: string;
  /** The resolved person (R-P7c): `entry_players.id`. The key one human's
   *  entries share across submissions — the desk's grouping identity, where
   *  before it had only `playerName` and eyes. Null on rows minted before
   *  the person spine. */
  entryPlayerId: string | null;
  /** The other half of this doubles pair (`entries.partner_entry_id`),
   *  written on BOTH halves at acceptance. Null for singles and for a
   *  nomination nobody has accepted. The partner's NAME is a join the desk
   *  already holds every row for — F-DM-35 was the key not being on the
   *  wire, not the name. */
  partnerEntryId: string | null;
  remarks: string | null;
  listOptOut: boolean;
  /** Set once Seam A has materialized this entry as a roster player. */
  committedPlayerId: string | null;
  submittedAt: string | null;
  withdrawnAt: string | null;
}

/** One form act, as much of it as the desk needs — mirrors the backend
 *  `EntrySubmissionDTO`.
 *
 *  `id` is the GROUPING KEY: the desk bands entries by it to show "these
 *  arrived on one form", which before R13 an operator had to infer by eye
 *  from a repeated email address — ambiguous exactly when it mattered,
 *  because one parent account legitimately submits many times.
 *
 *  `feeTotalCents` belongs to the act and not to any entry under it:
 *  tiered pricing prices the person, not the event, so three events for
 *  one player have one total between them rather than three. */
export interface EntrySubmissionDTO {
  id: string;
  accountEmail: string | null;
  accountName: string | null;
  feeTotalCents: number | null;
  submittedAt: string | null;
}

/** One committed entry: which entry became which roster player. */
export interface EntryCommitOutcomeDTO {
  id: string;
  playerId: string;
}

/** One skipped entry + the stable reason code. Spec §5: partial success is
 *  reported per-entry, not rolled back — so this is a normal outcome, not an
 *  error body. Codes: `UNMAPPABLE_EVENT` | `DRAW_NOT_EDITABLE` |
 *  `STATE_CONFLICT` | `INVALID_PLAYER`. */
export interface EntrySkipDTO {
  id: string;
  reason: string;
}

export interface EntryCommitResultDTO {
  committed: EntryCommitOutcomeDTO[];
  skipped: EntrySkipDTO[];
}

/** Server-computed control-plane signals (mirrors backend
 *  `api/workspace_signals.py`). Surfaced on `TournamentSummaryDTO.signals`. */
export interface AttentionReasonDTO {
  /** Stable machine code, e.g. "NO_ROSTER". */
  code: string;
  /** Human label, e.g. "No players added yet". */
  label: string;
}

interface ModuleCountsDTO {
  enabled: number;
  available: number;
  disabled: number;
  comingSoon: number;
}

interface CollaborationDTO {
  memberCount: number;
  activeInviteCount: number;
}

/** The inspector's metric triplet (`to do` = attention-reason count). */
interface MatchMetricsDTO {
  total: number;
  scheduled: number;
  toDo: number;
  /** Terminally-resolved matches (finished/retired; bracket: recorded
   *  results) — the Overview's live-progress readout. Optional for older
   *  payloads. */
  played?: number;
  /** Matches on a court right now (started; called deliberately excluded —
   *  its players are still walking). INS-4/OV-4. Optional for older payloads. */
  playing?: number;
  /** Courts with nothing playing on them. `null` when the workspace has no
   *  court count to subtract from — an unknown is not zero. */
  courtsFree?: number | null;
}

/** One upcoming match for the inspector's "Next up" list. `status` is
 *  schedule-derivable only ("scheduled") — live called/started state is not
 *  surfaced on the Hub (it lives in match_states; Operations Run is live). */
export interface NextMatchDTO {
  code: string;
  timeLabel: string | null;
  courtLabel: string | null;
  status: string;
  /** Identity, so a "Up next" row can be a door rather than a readout (OV-1).
   *  `source` matters as much as the id: Operations keys selection
   *  `{source}:{id}` because meet and bracket records are non-merged
   *  (ADR 0006). Optional for older payloads. */
  matchId?: string | null;
  source?: 'meet' | 'bracket' | null;
}

export interface WorkspaceSignalsDTO {
  health: 'good' | 'attention' | 'draft' | 'archived';
  attention: AttentionReasonDTO[];
  modules: ModuleCountsDTO;
  /** Per-kind readiness checklist (keys vary by kind), e.g. `{ roster: true }`. */
  setup: Record<string, boolean>;
  collaboration: CollaborationDTO;
  /** Per-workspace match metrics (redesign). Optional for older payloads. */
  matches?: MatchMetricsDTO;
  /** Next ≤3 upcoming matches (finished/on-court ones are filtered
   *  server-side since the 2026-07-09 audit). Optional / empty when none. */
  nextUp?: NextMatchDTO[];
  /** Lifecycle phase derived from real play state (2026-07-09 audit):
   *  setup → ready → live → complete. Optional for older payloads. */
  /** E4: the entries desk in numbers. Absent where there is no entry page,
   *  which is every local-mode workspace (invariant I3). Counts only — this
   *  rides on a summary the Hub renders for every workspace at once, and a
   *  control-plane payload carrying entrant data would be a disclosure
   *  surface with no route of its own to review. */
  entries?: {
    total: number;
    pending: number;
    waitlisted: number;
    confirmed: number;
    /** `confirmed` and not yet on the roster — what ENTRIES_NOT_COMMITTED
     *  counts, so the panel can say how many rather than only that there
     *  are some. */
    uncommitted: number;
    closed: boolean;
  } | null;
  // E4 (program Phase 9): three entries phases at the FRONT; the four play
  // phases keep their exact meanings. A workspace with no entry page never
  // reaches the first three.
  phase?:
    | 'announced'
    | 'entries_open'
    | 'entries_review'
    | 'setup'
    | 'ready'
    | 'live'
    | 'complete';
}

export interface TournamentSummaryDTO {
  id: string;
  name: string | null;
  status: TournamentStatus;
  kind: TournamentKind;
  tournamentDate: string | null;
  tournamentEndDate?: string | null;
  timeZone?: string;
  createdAt: string;
  updatedAt: string;
  /** Caller's role on this tournament — non-null in list responses
   *  because the list is filtered to the caller's memberships. */
  role: TournamentRole | null;
  /** Owner's email, denormalised at tournament-create time. Used by
   *  the "Shared with You" dashboard section. */
  ownerName: string | null;
  /** Persisted module catalog for this workspace (sub-project #1). Optional
   *  for backward compatibility with older payloads. */
  modules?: WorkspaceModuleDTO[];
  /** Server-computed control-plane signals (SP-A). Optional for backward
   *  compatibility with older payloads. */
  signals?: WorkspaceSignalsDTO;
}

export interface TournamentCreateDTO {
  name?: string | null;
  kind?: TournamentKind;
  tournamentDate?: string | null;
  tournamentEndDate?: string | null;
  timeZone?: string;
  courtCount?: number;
  /** Optional explicit module seed (control-plane templates). When present,
   *  the backend persists this set instead of the kind-derived one. */
  modules?: WorkspaceModuleDTO[];
}

export interface TournamentUpdateDTO {
  name?: string | null;
  status?: TournamentStatus;
  tournamentDate?: string | null;
  tournamentEndDate?: string | null;
  timeZone?: string;
}

// ---- Auth (self-hosted cookie sessions, SP-CLOUD-2) ----------------------

/** The signed-in identity from ``/auth/*``. In local mode this is the
 *  bootstrap identity (``isBootstrap: true``) — the no-login-wall path. */
export interface UserDTO {
  id: string;
  email: string;
  displayName?: string | null;
  emailVerified: boolean;
  isBootstrap: boolean;
  authMode: 'local' | 'cloud';
}

/** The workspace's public display capability link (owner-gated mint/rotate).
 *  ``url`` is a relative path — frontend prepends ``window.location.origin``. */
export interface DisplayTokenDTO {
  token: string;
  url: string;
}

/** The stored entry page as the operator sees it (SP-P7 adds the
 *  publication gates; the Sharing tab's card reads and flips them). */
export interface EntryPageDTO {
  slug: string;
  isOpen: boolean;
  introText: string | null;
  regulationsText: string | null;
  waiverRequired: boolean;
  regulationsVersion: number;
  regulationsUpdatedAt: string | null;
  feeSchedule: Record<string, number> | null;
  paymentInstructions: string | null;
  maxEventsPerPerson: number | null;
  disciplineCaps: Record<string, unknown> | null;
  collectPhone: boolean;
  venueName: string | null;
  venueAddress: string | null;
  entrantsPublished: boolean;
  drawsPublished: boolean;
  resultsPublished: boolean;
}

/** PATCH body for the publication card — patch semantics: only the flags
 *  the operator actually toggled travel. */
export interface EntryPagePublicationPatchDTO {
  entrantsPublished?: boolean;
  drawsPublished?: boolean;
  resultsPublished?: boolean;
}

// Invite links (Step 7)
export type InviteRole = 'operator' | 'viewer';

export interface InviteCreateDTO {
  role: InviteRole;
  /** SP-CLOUD-2: when set, this becomes an email invite — the link is
   *  delivered via the email seam and the invite expires. */
  email?: string;
}

export interface InviteCreatedDTO {
  token: string;
  /** Relative path — frontend prepends ``window.location.origin``. */
  url: string;
  tournamentId: string;
  role: InviteRole;
  createdAt: string;
  /** Recipient address for email invites; null for bare links. */
  email?: string | null;
}

export interface InviteSummaryDTO {
  token: string;
  tournamentId: string;
  role: InviteRole;
  createdAt: string;
  expiresAt: string | null;
  revokedAt: string | null;
  valid: boolean;
  /** Recipient address for email invites; null for bare links. */
  email?: string | null;
}

/** Public `GET /invites/{token}`. A 200 *means* the invite is
 *  acceptable — every other state (unknown, revoked, expired, workspace
 *  deleted) answers one uniform 404, so there are no lifecycle flags to
 *  read here. `InviteSummaryDTO` keeps them for the owner-facing
 *  listing, which is authenticated and may legitimately see them. */
export interface InviteResolveDTO {
  token: string;
  tournamentId: string;
  tournamentName: string | null;
  role: InviteRole;
}

export interface InviteAcceptedDTO {
  tournamentId: string;
  role: string;
  alreadyMember: boolean;
}

export interface TournamentMemberDTO {
  userId: string;
  role: string;
  joinedAt: string;
  /** SP-CLOUD-2: real identity from the users table. ``email`` is null
   *  for pre-account placeholder identities (unmigrated rows). */
  email?: string | null;
  displayName?: string | null;
}

// ---- Operator commands (Step F of the architecture-adjustment arc) -------

type MatchAction =
  | 'call_to_court'
  | 'start_match'
  | 'finish_match'
  | 'retire_match'
  | 'uncall'
  | 'assign_court'
  | 'postpone_match';

/**
 * Body of ``POST /tournaments/{tid}/commands``. The ``id`` is the
 * client-generated UUID used as the idempotency key; the same id
 * resubmitted gets the original outcome.
 */
export interface CommandRequestDTO {
  id: string;
  match_id: string;
  action: MatchAction;
  payload: Record<string, unknown> | null;
  seen_version: number;
}

/**
 * Successful (200) response body — carries the *current* match
 * state. Replay after a third-party update returns the current
 * (mutated) state, not the post-original-apply state.
 */
export interface CommandResponseDTO {
  command_id: string;
  match_id: string;
  status: 'scheduled' | 'called' | 'playing' | 'finished' | 'retired';
  version: number;
  court_id: number | null;
  time_slot: number | null;
  applied_at: string;
  replay: boolean;
}

/**
 * Body shape for 409 (state-machine conflict or stale version).
 * ``error`` discriminates between the two flavours; the frontend
 * branches on it to choose between "refetch and retry" and "show
 * permanent rejection."
 */
export interface CommandConflictDTO {
  error: 'conflict' | 'stale_version';
  match_id: string;
  message: string;
  current_status?: string;
  attempted_status?: string;
  current_version?: number;
  seen_version?: number;
}

// Constraint Visualization Types
export interface ConstraintViolation {
  type: 'rest' | 'overlap' | 'availability' | 'court_capacity' | 'game_proximity_min' | 'game_proximity_max';
  severity: 'hard' | 'soft';
  playerIds: string[];
  matchIds: string[];
  description: string;
}
