"""step1_initial_persistence

Revision ID: c6361600d776
Revises: 
Create Date: 2026-05-13 01:56:27.114681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6361600d776'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournaments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tournament_date', sa.String(length=32), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_states',
    sa.Column('tournament_id', sa.Uuid(), nullable=False),
    sa.Column('match_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('called_at', sa.String(length=40), nullable=True),
    sa.Column('actual_start_time', sa.String(length=40), nullable=True),
    sa.Column('actual_end_time', sa.String(length=40), nullable=True),
    sa.Column('score_side_a', sa.Integer(), nullable=True),
    sa.Column('score_side_b', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('original_slot_id', sa.Integer(), nullable=True),
    sa.Column('original_court_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tournament_id', 'match_id')
    )
    op.create_table('tournament_backups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tournament_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=260), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournament_backups')
    op.drop_table('match_states')
    op.drop_table('tournaments')
    # ### end Alembic commands ###
