"""Generated customer-facing brand constants.

Generated by ``tools/generate-brand.mjs`` from ``packages/brand/brand.json``.
Do not edit this file directly. Compatibility-sensitive protocol identifiers
remain deliberately independent of these display values.
"""

SCHEMA_VERSION = 1
PRODUCT_NAME = "ShuttleWorks"
PUBLIC_PRODUCT_NAME = "ShuttleWorks Tournaments"
PRODUCT_MONOGRAM = "SW"
COMPANY_NAME = "Yunavero"
COMPANY_DOMAIN = "yunavero.com"
ENDORSEMENT = "by Yunavero"
OPERATOR_HOSTNAME = "app.yunavero.com"
ENTRANT_HOSTNAME = "play.yunavero.com"
BRAND_SIGNATURE = f"{PRODUCT_NAME} {ENDORSEMENT}"
