// Generated by tools/generate-brand.mjs from packages/brand/brand.json.
// Do not edit this file directly.

export type BrandConfig = Readonly<{
  schemaVersion: number;
  productName: string;
  publicProductName: string;
  productMonogram: string;
  companyName: string;
  companyDomain: string;
  endorsement: string;
  operatorHostname: string;
  entrantHostname: string;
}>;

export const BRAND: BrandConfig = Object.freeze({
  schemaVersion: 1,
  productName: "ShuttleWorks",
  publicProductName: "ShuttleWorks Tournaments",
  productMonogram: "SW",
  companyName: "Yunavero",
  companyDomain: "yunavero.com",
  endorsement: "by Yunavero",
  operatorHostname: "app.yunavero.com",
  entrantHostname: "play.yunavero.com",
});

export const BRAND_SIGNATURE = `${BRAND.productName} ${BRAND.endorsement}`;

export function brandedTitle(page: string): string {
  return `${page} · ${BRAND.publicProductName}`;
}
