/**
 * The parity oracle (R-DM-9a, SP-DM-3 P0): `api/dto.ts` is checked against
 * the generated `api/dto.generated.ts` shapes, key by key.
 *
 * `dto.ts:14` says "DO NOT EDIT THIS FILE WITHOUT VERIFYING IT MATCHES
 * dto.generated.ts". Until now that verification was a human's eyes, and
 * F-DM-28a/28b are what the eyes missed. Freshness of the generated file
 * itself is the backend half of this oracle:
 * `tests/backend/test_dto_generated_freshness.py`.
 *
 * Keys only, by ruling — types and optionality are not policed (P0 plan,
 * Global Constraints).
 *
 * Why the two `dto.generated.ts` exclusions stay (re-justified 2026-08-24,
 * SP-DM-3 P0). `knip.json` — src/api/dto.generated.ts has no importer BY
 * DESIGN: this file reads it as TEXT (the R-DM-9a parity oracle), which
 * gives knip no import edge to see. The note lives here because knip's
 * schema rejects unknown keys, so `knip.json` cannot carry a comment.
 * `vitest.config.ts` coverage — the generated file is types-only and emits
 * no runtime code, so it can only ever report 0%. Neither exclusion leaves
 * it unpoliced; this test is what polices it.
 */
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

const API_DIR = resolve(__dirname, '..');

/** Every generated schema name -> its property names.
 *  ponytail: indentation regex over a machine-formatted file, not a TS
 *  parse. The pinned floor in the first test is what makes a formatting
 *  change fail loudly instead of emptying the comparison.
 *
 *  The scan is SCOPED to `export interface components`: the sibling `paths`
 *  and `operations` interfaces carry their own 8-space `parameters:`/
 *  `responses:`/`requestBody:` blocks, which an unscoped scan mistakes for
 *  schemas named after them. Same scoping as the Python twin. */
export function parseGenerated(source: string): Record<string, Set<string>> {
  const out: Record<string, Set<string>> = {};
  let current: string | null = null;
  let inComponents = false;
  for (const line of source.split(/\r?\n/)) {
    if (!inComponents) {
      inComponents = line.startsWith('export interface components');
      continue;
    }
    if (line.startsWith('}')) break;
    const open = /^ {8}([A-Za-z_][A-Za-z0-9_]*): \{$/.exec(line);
    if (open) {
      current = open[1];
      out[current] = new Set();
      continue;
    }
    if (!current) continue;
    const field = /^ {12}([A-Za-z_$][A-Za-z0-9_$]*)\??:/.exec(line);
    if (field) out[current].add(field[1]);
    else if (/^ {8}\};$/.test(line)) current = null;
  }
  return out;
}

/** Every top-level `export interface|type X { ... }` -> its member names.
 *  `[^{]*` absorbs `extends Y` and generics; unions without a body (e.g.
 *  `export type X = 'a' | 'b';`) have no `{` and are correctly skipped. */
export function parseHand(source: string): Record<string, Set<string>> {
  const out: Record<string, Set<string>> = {};
  let current: string | null = null;
  for (const line of source.split(/\r?\n/)) {
    const open = /^export (?:interface|type) ([A-Za-z_][A-Za-z0-9_]*)[^{]*\{/.exec(line);
    if (open) {
      current = open[1];
      out[current] = new Set();
      continue;
    }
    if (!current) continue;
    const field = /^ {2}([A-Za-z_$][A-Za-z0-9_$]*)\??:/.exec(line);
    if (field) out[current].add(field[1]);
    else if (/^\}/.test(line)) current = null;
  }
  return out;
}

/** F-DM-49: the same shape under two names.
 *  The last three are pure name-suffix mismatches (a `DTO` suffix the wire
 *  lacks, or one it has and the hand type lacks) - all three pair with zero
 *  key divergence, so they are naming drift, not shape drift. */
const ALIASES: Record<string, string> = {
  EntryDTO: 'EntryDeskRowDTO',
  CommandRequestDTO: 'CommandRequest',
  CommandResponseDTO: 'CommandResponse',
  ProposedMove: 'ProposedMoveDTO',
};

/** Hand shapes with NO wire twin, each with the reason it has none.
 *  This is the structural close of the unpoliced-shape class: `divergences()`
 *  skips any hand shape it cannot pair, so without this map a shape drifts
 *  unpoliced simply by being forgotten. Mirrors the entrant test's
 *  `unpaired` (apps/entrant/tests/dtoParity.test.ts). The exhaustiveness
 *  test below is what holds it to reality in BOTH directions - a shape that
 *  GAINS a wire twin must be promoted out of here into a real pair. */
const UNPAIRED: Record<string, string> = {
  SetScore:
    'Client-local set score. Wire candidate twin `MatchScore` is field-identical ({sideA, sideB}); aliasing it is a naming ruling and is deliberately not forced in P0.',
  LiveScheduleState:
    'Client-local aggregate (currentTime + a matchId->MatchStateDTO map + lastSynced) assembled by the polling hooks; the wire never sends this envelope.',
  SolverProgressEvent:
    'SSE payload for the solver-progress stream. OpenAPI models the ROUTE, not the event bodies, so there is no schema to pair against.',
  SolverModelBuiltEvent:
    'SSE "model_built" payload. Same reason as SolverProgressEvent: OpenAPI does not model text/event-stream event bodies.',
  SolverPhaseEvent:
    'SSE "phase" payload. Same reason as SolverProgressEvent: OpenAPI does not model text/event-stream event bodies.',
  ConstraintViolation:
    'Constraint-visualisation type. Wire candidate twin `SoftViolation` overlaps only on type/description; pairing them would need a shape decision, which is P1/P4 territory.',
  CommandConflictDTO:
    'Command-path 409 body. Wire candidate twin `ValidationConflict` is a different thing (schedule validation, not command conflict) despite the near-name; deliberately not forced.',
};

type AllowEntry = { shape: string; field: string; side: string; kind: string; why: string };

const generatedSource = readFileSync(resolve(API_DIR, 'dto.generated.ts'), 'utf-8');
const handSource = readFileSync(resolve(API_DIR, 'dto.ts'), 'utf-8');
const generated = parseGenerated(generatedSource);
const hand = parseHand(handSource);
// JSON.parse rather than an import: `resolveJsonModule` is off in
// tsconfig.app.json, same as store/__tests__/nonSchedulingKeys.parity.test.ts.
const allowlist: AllowEntry[] = JSON.parse(
  readFileSync(resolve(__dirname, 'dtoParity.allowlist.json'), 'utf-8'),
);

/** Every divergent (shape, field, side) the oracle can see right now. */
export function divergences(): AllowEntry[] {
  const found: AllowEntry[] = [];
  for (const [name, handKeys] of Object.entries(hand)) {
    const wire = generated[ALIASES[name] ?? name];
    // No wire twin: nothing to compare. Not a hole - the "every hand shape is
    // either paired or explicitly unpaired" test below proves every name that
    // lands here is a declared `UNPAIRED` entry with a reason.
    if (!wire) continue;
    for (const k of handKeys) if (!wire.has(k)) found.push({ shape: name, field: k, side: 'hand-only', kind: '', why: '' });
    for (const k of wire) if (!handKeys.has(k)) found.push({ shape: name, field: k, side: 'generated-only', kind: '', why: '' });
  }
  return found;
}

const key = (e: { shape: string; field: string; side: string }) => `${e.shape}.${e.field}:${e.side}`;

describe('console DTO parity oracle', () => {
  it('parses both files (guards the parsers themselves)', () => {
    // Actuals today: 177 generated schemas, 64 hand shapes, 57 pairs.
    // These floors are PARSER guards, not a ratchet: lower them freely when
    // shapes are deliberately deleted (R-DM-9(c)'s end-state shrinks dto.ts;
    // P1's own gate is 9 declarations -> <=3). Only the ALLOW-LIST cap below
    // is a ratchet, and raising that one is a ruling.
    // A floor sits AT or BELOW the actual by design - it exists to catch a
    // parser that stopped seeing things, not to freeze the count.
    expect(Object.keys(generated).length).toBeGreaterThanOrEqual(175);
    expect(Object.keys(hand).length).toBeGreaterThanOrEqual(64);
    // Every `export interface` HAS a body, so every one must have parsed -
    // a silently skipped shape is the parser's only fail-dangerous mode.
    for (const [, name] of handSource.matchAll(/^export interface ([A-Za-z_][A-Za-z0-9_]*)/gm)) {
      expect(Object.keys(hand)).toContain(name);
    }
    const paired = Object.keys(hand).filter((n) => generated[ALIASES[n] ?? n]);
    expect(paired.length).toBeGreaterThanOrEqual(57);
    // FIELD-level parser drift lands here, not in the keys test: a schema
    // parsed to zero fields means the indentation the field regex keys on
    // moved. Without this, that shows up downstream as "every generated key
    // vanished", whose remedy reads as "regenerate" - the wrong diagnosis.
    const empty = [...Object.entries(generated), ...Object.entries(hand)]
      .filter(([, keys]) => keys.size === 0)
      .map(([name]) => name);
    expect(empty).toEqual([]);
  });

  it('every hand shape is either paired or explicitly unpaired with a reason', () => {
    // One assertion, three failure modes, all of them the point:
    //  - a hand shape with no twin and no UNPAIRED entry (drift unpoliced by
    //    being forgotten - the hole this test closes);
    //  - a stale UNPAIRED entry for a shape that no longer exists;
    //  - an UNPAIRED shape that GAINED a wire twin, which drops off the left
    //    side and so forces promotion to a real (policed) pair.
    const noTwin = Object.keys(hand).filter((n) => !generated[ALIASES[n] ?? n]);
    expect(noTwin.sort()).toEqual(Object.keys(UNPAIRED).sort());
    for (const why of Object.values(UNPAIRED)) expect(why.length).toBeGreaterThan(20);
  });

  it('dto.ts matches the generated shapes, except the allow-listed divergences', () => {
    const allowed = new Set(allowlist.map(key));
    const unexpected = divergences().filter((d) => !allowed.has(key(d)));
    expect(unexpected).toEqual([]);
  });

  it('the allow-list only shrinks: every entry is still a real divergence', () => {
    const live = new Set(divergences().map(key));
    const stale = allowlist.filter((e) => !live.has(key(e)));
    expect(stale).toEqual([]); // fixed a divergence? delete its allow-list line.
  });

  it('the allow-list is capped and every entry cites its reason', () => {
    // RATCHET: this number may only go DOWN. Raising it is a ruling, not an edit.
    expect(allowlist.length).toBeLessThanOrEqual(19);
    for (const e of allowlist) {
      expect(e.why).toMatch(/F-DM-\d+|R-DM-\d+|ADR \d+/);
      expect(['violation', 'accepted']).toContain(e.kind);
    }
  });
});

describe('NC: the oracle SEES F-DM-28a (it is allow-listed, not silenced)', () => {
  it('reports PlayerDTO status / withdrawalReason / withdrawnAt as hand-only divergences', () => {
    // The allow-list stops these from failing the suite. This asserts the
    // oracle still DETECTS them - so deleting the allow-list entries is the
    // only way to make them go away, and quietly widening the allow-list
    // cannot hide them. R-DM-9a: "ratcheted to zero, never silenced".
    const seen = divergences()
      .filter((d) => d.shape === 'PlayerDTO')
      .map((d) => d.field)
      .sort();
    expect(seen).toEqual(['status', 'withdrawalReason', 'withdrawnAt']);
    const listed = allowlist.filter((e) => e.shape === 'PlayerDTO');
    expect(listed).toHaveLength(3);
    for (const e of listed) {
      expect(e.kind).toBe('violation');
      expect(e.why).toContain('F-DM-28a');
    }
  });
});
