/**
 * The parity oracle (R-DM-9a, SP-DM-3 P0): `api/dto.ts` is checked against
 * the generated `api/dto.generated.ts` shapes, key by key.
 *
 * `dto.ts:14` says "DO NOT EDIT THIS FILE WITHOUT VERIFYING IT MATCHES
 * dto.generated.ts". Until now that verification was a human's eyes, and
 * F-DM-28a/28b are what the eyes missed. Freshness of the generated file
 * itself is the backend half of this oracle:
 * `tests/backend/test_dto_generated_freshness.py`.
 *
 * Keys only, by ruling — types and optionality are not policed (P0 plan,
 * Global Constraints).
 */
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

const API_DIR = resolve(__dirname, '..');

/** Every generated schema name -> its property names.
 *  ponytail: indentation regex over a machine-formatted file, not a TS
 *  parse. The pinned floor in the first test is what makes a formatting
 *  change fail loudly instead of emptying the comparison.
 *
 *  The scan is SCOPED to `export interface components`: the sibling `paths`
 *  and `operations` interfaces carry their own 8-space `parameters:`/
 *  `responses:`/`requestBody:` blocks, which an unscoped scan mistakes for
 *  schemas named after them. Same scoping as the Python twin. */
export function parseGenerated(source: string): Record<string, Set<string>> {
  const out: Record<string, Set<string>> = {};
  let current: string | null = null;
  let inComponents = false;
  for (const line of source.split(/\r?\n/)) {
    if (!inComponents) {
      inComponents = line.startsWith('export interface components');
      continue;
    }
    if (line.startsWith('}')) break;
    const open = /^ {8}([A-Za-z_][A-Za-z0-9_]*): \{$/.exec(line);
    if (open) {
      current = open[1];
      out[current] = new Set();
      continue;
    }
    if (!current) continue;
    const field = /^ {12}([A-Za-z_$][A-Za-z0-9_$]*)\??:/.exec(line);
    if (field) out[current].add(field[1]);
    else if (/^ {8}\};$/.test(line)) current = null;
  }
  return out;
}

/** Every top-level `export interface|type X { ... }` -> its member names.
 *  `[^{]*` absorbs `extends Y` and generics; unions without a body (e.g.
 *  `export type X = 'a' | 'b';`) have no `{` and are correctly skipped. */
export function parseHand(source: string): Record<string, Set<string>> {
  const out: Record<string, Set<string>> = {};
  let current: string | null = null;
  for (const line of source.split(/\r?\n/)) {
    const open = /^export (?:interface|type) ([A-Za-z_][A-Za-z0-9_]*)[^{]*\{/.exec(line);
    if (open) {
      current = open[1];
      out[current] = new Set();
      continue;
    }
    if (!current) continue;
    const field = /^ {2}([A-Za-z_$][A-Za-z0-9_$]*)\??:/.exec(line);
    if (field) out[current].add(field[1]);
    else if (/^\}/.test(line)) current = null;
  }
  return out;
}

/** F-DM-49: the same shape under two names. */
const ALIASES: Record<string, string> = { EntryDTO: 'EntryDeskRowDTO' };

type AllowEntry = { shape: string; field: string; side: string; kind: string; why: string };

const generatedSource = readFileSync(resolve(API_DIR, 'dto.generated.ts'), 'utf-8');
const handSource = readFileSync(resolve(API_DIR, 'dto.ts'), 'utf-8');
const generated = parseGenerated(generatedSource);
const hand = parseHand(handSource);
// JSON.parse rather than an import: `resolveJsonModule` is off in
// tsconfig.app.json, same as store/__tests__/nonSchedulingKeys.parity.test.ts.
const allowlist: AllowEntry[] = JSON.parse(
  readFileSync(resolve(__dirname, 'dtoParity.allowlist.json'), 'utf-8'),
);

/** Every divergent (shape, field, side) the oracle can see right now. */
export function divergences(): AllowEntry[] {
  const found: AllowEntry[] = [];
  for (const [name, handKeys] of Object.entries(hand)) {
    const wire = generated[ALIASES[name] ?? name];
    if (!wire) continue; // frontend-private type: no wire twin, nothing to police
    for (const k of handKeys) if (!wire.has(k)) found.push({ shape: name, field: k, side: 'hand-only', kind: '', why: '' });
    for (const k of wire) if (!handKeys.has(k)) found.push({ shape: name, field: k, side: 'generated-only', kind: '', why: '' });
  }
  return found;
}

const key = (e: { shape: string; field: string; side: string }) => `${e.shape}.${e.field}:${e.side}`;

describe('console DTO parity oracle', () => {
  it('parses both files (guards the parsers themselves)', () => {
    // Pinned at da254eed: 177 generated schemas, 64 hand shapes, 54 pairs.
    // These floors are PARSER guards, not a ratchet: lower them freely when
    // shapes are deliberately deleted (R-DM-9(c)'s end-state shrinks dto.ts;
    // P1's own gate is 9 declarations -> <=3). Only the ALLOW-LIST cap below
    // is a ratchet, and raising that one is a ruling.
    expect(Object.keys(generated).length).toBeGreaterThanOrEqual(175);
    expect(Object.keys(hand).length).toBeGreaterThanOrEqual(64);
    // Every `export interface` HAS a body, so every one must have parsed -
    // a silently skipped shape is the parser's only fail-dangerous mode.
    for (const [, name] of handSource.matchAll(/^export interface ([A-Za-z_][A-Za-z0-9_]*)/gm)) {
      expect(Object.keys(hand)).toContain(name);
    }
    const paired = Object.keys(hand).filter((n) => generated[ALIASES[n] ?? n]);
    expect(paired.length).toBeGreaterThanOrEqual(53);
  });

  it('dto.ts matches the generated shapes, except the allow-listed divergences', () => {
    const allowed = new Set(allowlist.map(key));
    const unexpected = divergences().filter((d) => !allowed.has(key(d)));
    expect(unexpected).toEqual([]);
  });

  it('the allow-list only shrinks: every entry is still a real divergence', () => {
    const live = new Set(divergences().map(key));
    const stale = allowlist.filter((e) => !live.has(key(e)));
    expect(stale).toEqual([]); // fixed a divergence? delete its allow-list line.
  });

  it('the allow-list is capped and every entry cites its reason', () => {
    // RATCHET: this number may only go DOWN. Raising it is a ruling, not an edit.
    expect(allowlist.length).toBeLessThanOrEqual(19);
    for (const e of allowlist) {
      expect(e.why).toMatch(/F-DM-\d+|R-DM-\d+|ADR \d+/);
      expect(['violation', 'accepted']).toContain(e.kind);
    }
  });
});
