import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const root = resolve(import.meta.dirname, '..')
const sourcePath = resolve(root, 'packages/brand/brand.json')
const tsPath = resolve(root, 'packages/brand/generated.ts')
const pyPath = resolve(root, 'apps/api/src/core/brand.py')
const brand = JSON.parse(readFileSync(sourcePath, 'utf8'))

const required = [
  'schemaVersion',
  'productName',
  'publicProductName',
  'productMonogram',
  'companyName',
  'companyDomain',
  'endorsement',
  'operatorHostname',
  'entrantHostname',
]

for (const key of required) {
  if (!(key in brand) || brand[key] === '') {
    throw new Error(`packages/brand/brand.json is missing ${key}`)
  }
}
if (brand.schemaVersion !== 1) throw new Error('unsupported brand schemaVersion')
if (brand.operatorHostname === brand.entrantHostname) {
  throw new Error('operatorHostname and entrantHostname must remain separate origins')
}

const js = (value) => JSON.stringify(value)
const py = (value) => JSON.stringify(value, null, 0)
const upperSnake = (value) => value.replace(/[A-Z]/g, (letter) => `_${letter}`).toUpperCase()

const ts = `// Generated by tools/generate-brand.mjs from packages/brand/brand.json.
// Do not edit this file directly.

export type BrandConfig = Readonly<{
${required.map((key) => `  ${key}: ${key === 'schemaVersion' ? 'number' : 'string'};`).join('\n')}
}>;

export const BRAND: BrandConfig = Object.freeze({
${required.map((key) => `  ${key}: ${js(brand[key])},`).join('\n')}
});

export const BRAND_SIGNATURE = \`\${BRAND.productName} \${BRAND.endorsement}\`;

export function brandedTitle(page: string): string {
  return \`\${page} · \${BRAND.publicProductName}\`;
}
`

const python = `"""Generated customer-facing brand constants.

Generated by \`\`tools/generate-brand.mjs\`\` from \`\`packages/brand/brand.json\`\`.
Do not edit this file directly. Compatibility-sensitive protocol identifiers
remain deliberately independent of these display values.
"""

${required.map((key) => `${upperSnake(key)} = ${py(brand[key])}`).join('\n')}
BRAND_SIGNATURE = f"{PRODUCT_NAME} {ENDORSEMENT}"
`

const outputs = [[tsPath, ts], [pyPath, python]]
if (process.argv.includes('--check')) {
  const stale = outputs.filter(([path, content]) => readFileSync(path, 'utf8') !== content)
  if (stale.length) {
    console.error(`Generated brand files are stale: ${stale.map(([path]) => path).join(', ')}`)
    process.exit(1)
  }
  console.log('brand:check — generated TypeScript and Python constants are current')
} else {
  for (const [path, content] of outputs) writeFileSync(path, content)
  console.log('brand:generate — updated TypeScript and Python constants')
}
