#!/usr/bin/env python3
"""Render the shared lifecycle contract. --check compares isolated temp output."""
from __future__ import annotations
import argparse
from dataclasses import asdict
import difflib
import json
from pathlib import Path
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "apps/api/src"))
from core import state_machines  # noqa: F401,E402
from core.state_machine import REGISTRY  # noqa: E402


def artifacts():
    machines = {}
    lines = ["# State machines", "", "Generated by `tools/generate_state_machines.py`; edit the Python definitions.", "",
             "See [implementation status and transaction semantics](./state-machines-implementation.md).", ""]
    for name, machine in sorted(REGISTRY.items()):
        data = asdict(machine)
        for field in ("states", "initial", "terminal"):
            data[field] = sorted(data[field])
        # Object keys retain literal types under TypeScript resolveJsonModule.
        data["state_keys"] = {state: state for state in sorted(machine.states)}
        data["event_keys"] = {event: event for event in sorted({t.event for t in machine.transitions})}
        for transition in data["transitions"]:
            transition["from_states"] = sorted(transition["from_states"])
        machines[name] = data
        lines += [f"## {name} (version {machine.version})", "",
                  f"Initial: {', '.join(data['initial'])}. Terminal: {', '.join(data['terminal']) or 'none'}.", "",
                  "| Event | From | To | Actor | Guard | Consequential | Meaning |",
                  "| --- | --- | --- | --- | --- | --- | --- |"]
        for t in data["transitions"]:
            lines.append(f"| {t['event']} | {', '.join(t['from_states'])} | {t['to']} | {t['actor']} | {t['guard'] or '—'} | {str(t['consequential']).lower()} | {t['description']} |")
        lines += [""]
    return {"packages/shared-contract/state-machines.json": json.dumps({"machines": machines}, indent=2) + "\n",
            "docs/reference/state-machines.md": "\n".join(lines)}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output-root", type=Path, default=ROOT)
    args = parser.parse_args()
    failed = False
    with tempfile.TemporaryDirectory() as temporary:
        destination = Path(temporary) if args.check else args.output_root
        for relative, content in artifacts().items():
            path = destination / relative
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            if args.check:
                expected = args.output_root / relative
                before = expected.read_text() if expected.exists() else ""
                if before != path.read_text():
                    failed = True
                    sys.stderr.writelines(difflib.unified_diff(before.splitlines(True), content.splitlines(True), fromfile=relative, tofile="generated/" + relative))
    return int(failed)


if __name__ == "__main__":
    raise SystemExit(main())
