server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    disable_symlinks on;
    location = /operator-console-surface-book.pdf {
        try_files $uri =404;
    }
    location = /public-entrant-surface-book.pdf {
        try_files $uri =404;
    }
    location / {
        return 404;
    }
}
