server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    disable_symlinks on;
    autoindex on;
    autoindex_exact_size off;
    autoindex_localtime off;

    location ~ (^|/)\.(?!well-known/) {
        deny all;
    }
    location / {
        try_files $uri $uri/ =404;
    }
}
